-- Seed the canonical Compliance Guard rule catalog from the complete JSON baseline.
--
-- The complete source document is retained in JSONB and expanded into queryable columns.
-- This migration is additive and idempotent; it does not delete existing Compliance Guard data.
-- 署名：Codex，合规卫士开发 Agent
-- 时间：2026-09-14

BEGIN;

CREATE TABLE IF NOT EXISTS guard_rule_catalog_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  version VARCHAR(64) NOT NULL UNIQUE,
  schema_version VARCHAR(32) NOT NULL DEFAULT '',
  status VARCHAR(64) NOT NULL DEFAULT 'draft',
  title VARCHAR(255) NOT NULL DEFAULT '',
  purpose TEXT NOT NULL DEFAULT '',
  execution_policy JSONB NOT NULL DEFAULT '{}'::jsonb,
  field_definitions JSONB NOT NULL DEFAULT '{}'::jsonb,
  migration_notes JSONB NOT NULL DEFAULT '{}'::jsonb,
  definition JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS guard_rule_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  catalog_id UUID REFERENCES guard_rule_catalog_versions(id),
  tenant_id BIGINT,
  rule_code VARCHAR(128) NOT NULL,
  legacy_rule_number VARCHAR(32) NOT NULL DEFAULT '',
  rule_name VARCHAR(255) NOT NULL DEFAULT '',
  category VARCHAR(128) NOT NULL DEFAULT '',
  subject VARCHAR(32) NOT NULL,
  source_kind VARCHAR(32) NOT NULL DEFAULT 'platform',
  version VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  applicable_rule_sets JSONB NOT NULL DEFAULT '[]'::jsonb,
  legal_basis JSONB NOT NULL DEFAULT '[]'::jsonb,
  judgment_standard TEXT NOT NULL DEFAULT '',
  trigger_conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  exclusion_conditions JSONB NOT NULL DEFAULT '[]'::jsonb,
  violation_examples JSONB NOT NULL DEFAULT '[]'::jsonb,
  compliant_examples JSONB NOT NULL DEFAULT '[]'::jsonb,
  fact_definition TEXT NOT NULL DEFAULT '',
  required_evidence JSONB NOT NULL DEFAULT '[]'::jsonb,
  required_external_facts JSONB NOT NULL DEFAULT '[]'::jsonb,
  indeterminate_boundary TEXT NOT NULL DEFAULT '',
  output_type VARCHAR(64) NOT NULL DEFAULT '',
  review_priority VARCHAR(32) NOT NULL DEFAULT '',
  validation_status VARCHAR(64) NOT NULL DEFAULT '',
  source_basis JSONB NOT NULL DEFAULT '[]'::jsonb,
  definition JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS guard_rule_set_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  catalog_id UUID REFERENCES guard_rule_catalog_versions(id),
  tenant_id BIGINT,
  rule_set_code VARCHAR(128) NOT NULL,
  rule_set_name VARCHAR(255) NOT NULL DEFAULT '',
  subject VARCHAR(32) NOT NULL,
  source_kind VARCHAR(32) NOT NULL DEFAULT 'platform',
  version VARCHAR(64) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'draft',
  role_codes JSONB NOT NULL DEFAULT '[]'::jsonb,
  source_types JSONB NOT NULL DEFAULT '[]'::jsonb,
  applicability JSONB NOT NULL DEFAULT '{}'::jsonb,
  notes TEXT NOT NULL DEFAULT '',
  definition JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  published_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS guard_rule_set_rule_versions (
  rule_set_version_id UUID NOT NULL REFERENCES guard_rule_set_versions(id) ON DELETE CASCADE,
  rule_version_id UUID NOT NULL REFERENCES guard_rule_versions(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (rule_set_version_id, rule_version_id)
);

ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS catalog_id UUID;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS legacy_rule_number VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS category VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS applicable_rule_sets JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS legal_basis JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS judgment_standard TEXT NOT NULL DEFAULT '';
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS trigger_conditions JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS exclusion_conditions JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS violation_examples JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS compliant_examples JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS fact_definition TEXT NOT NULL DEFAULT '';
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS required_evidence JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS required_external_facts JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS indeterminate_boundary TEXT NOT NULL DEFAULT '';
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS output_type VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS review_priority VARCHAR(32) NOT NULL DEFAULT '';
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS validation_status VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS source_basis JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_versions ADD COLUMN IF NOT EXISTS definition JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE guard_rule_set_versions ADD COLUMN IF NOT EXISTS catalog_id UUID;
ALTER TABLE guard_rule_set_versions ADD COLUMN IF NOT EXISTS role_codes JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_set_versions ADD COLUMN IF NOT EXISTS source_types JSONB NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE guard_rule_set_versions ADD COLUMN IF NOT EXISTS notes TEXT NOT NULL DEFAULT '';
ALTER TABLE guard_rule_set_versions ADD COLUMN IF NOT EXISTS definition JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE guard_rule_set_rule_versions ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS guard_rule_versions_identity_uq ON guard_rule_versions (COALESCE(tenant_id, 0), rule_code, version);
CREATE INDEX IF NOT EXISTS guard_rule_versions_scope_idx ON guard_rule_versions (tenant_id, subject, status);
CREATE UNIQUE INDEX IF NOT EXISTS guard_rule_set_versions_identity_uq ON guard_rule_set_versions (COALESCE(tenant_id, 0), rule_set_code, version);
CREATE INDEX IF NOT EXISTS guard_rule_set_versions_lookup_idx ON guard_rule_set_versions (tenant_id, subject, rule_set_code, status, version DESC);
CREATE INDEX IF NOT EXISTS guard_rule_set_rule_versions_rule_idx ON guard_rule_set_rule_versions (rule_version_id);

WITH canonical AS (
  SELECT 
$canonical$
{
  "schema_version": "1.0",
  "status": "canonical_current_baseline",
  "title": "合规卫士沟通与内容合规规则集",
  "version": "20260911.1",
  "purpose": "本文件是合规卫士当前规则讨论和后续实现的唯一基础。它自包含保存规则定义、业务说明、适用范围、判断边界和规则集成员关系，后续不需要回看历史规则文档或历史迁移 SQL。",
  "execution_policy": {
    "system_role": "合规引擎只发现需要医院查看的具体问题，不自动确认违规、不定责、不处罚。",
    "finding_granularity": "一次输入资料与一条规则最多形成一条发现；同一输入同一规则的多处证据合并到一条发现；同一输入不同规则分别形成发现；不同输入不得合并。",
    "llm_policy": "规则为大模型提供检查范围、判断标准、例外和证据要求；最终结论由医院复核。",
    "status_policy": "published 表示已进入对应规则集；draft 表示定义已保留但当前不应仅凭现有输入自动产生正式待核查发现。",
    "source_policy": "平台规则和医院本地规则分开管理；本院规则可以补充或收严平台规则，不能静默放宽平台底线。"
  },
  "field_definitions": {
    "rule_code": "规则的稳定编码。",
    "legacy_rule_number": "历史业务规则编号，仅用于追溯，不改变当前规则身份。",
    "subject": "规则处理的资料类型：communication 或 content。",
    "applicable_rule_sets": "规则进入哪些场景规则集。",
    "status": "当前发布状态。published 进入规则集，draft 只保留定义和待补资料要求。",
    "judgment_standard": "大模型和复核人员判断时必须回答的业务问题。",
    "trigger_conditions": "值得检查的表述或事实组合，不等于自动确认违规。",
    "exclusion_conditions": "出现这些条件时，不应仅凭本规则形成肯定性发现，或应降低为需要补充资料的候选。",
    "required_evidence": "发现和人工复核应尽量提供的证据。",
    "required_external_facts": "录音或内容本身之外必须补充的事实。",
    "indeterminate_boundary": "仅凭当前输入无法确定的边界。",
    "validation_status": "当前规则的验证状态。"
  },
  "rule_sets": [
    {
      "code": "communication.doctor.outpatient",
      "name": "医生门诊沟通规则集",
      "subject": "communication",
      "role_codes": ["doctor", "doctor_assistant"],
      "source_types": ["recording"],
      "status": "published",
      "included_rule_codes": [
        "communication.guarantee.direct",
        "communication.guarantee.absolute",
        "communication.guarantee.case",
        "communication.guarantee.duration",
        "communication.misleading.data_unverified",
        "communication.fear.exaggeration",
        "communication.fear.panic",
        "communication.fear.compare",
        "communication.scope.cross_department",
        "communication.scope.untrained_technology"
      ],
      "notes": "涉及价格成交、内容发布和必须核验外部事实的规则暂不作为仅凭医生录音自动检查的正式规则。"
    },
    {
      "code": "communication.consultant.consultation",
      "name": "咨询师咨询成交沟通规则集",
      "subject": "communication",
      "role_codes": ["consultant"],
      "source_types": ["recording"],
      "status": "published",
      "included_rule_codes": [
        "communication.guarantee.direct",
        "communication.guarantee.absolute",
        "communication.guarantee.case",
        "communication.guarantee.duration",
        "communication.misleading.exclusivity",
        "communication.misleading.disparage",
        "communication.misleading.urgency",
        "communication.misleading.data_unverified",
        "communication.fear.exaggeration",
        "communication.fear.panic",
        "communication.fear.compare",
        "communication.price.on_site_increase"
      ],
      "notes": "需要价格、活动或预约事实的规则保留为候选规则；没有外部事实时不得自动认定。"
    },
    {
      "code": "content.pre_publish",
      "name": "宣传内容发布前检查规则集",
      "subject": "content",
      "role_codes": [],
      "source_types": ["content_item", "script", "copy", "image_text"],
      "status": "draft",
      "included_rule_codes": [
        "content.price.false_original",
        "content.price.hidden_fee",
        "content.data.unverified",
        "content.privacy.patient",
        "content.honor.unverified"
      ],
      "notes": "内容中心正式接入和价格、授权、资质资料接入后发布。"
    }
  ],
  "rules": [
    {
      "rule_code": "communication.guarantee.direct",
      "legacy_rule_number": "1.1",
      "name": "直接保证诊疗结果",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条：不得对诊疗效果作出保证性承诺。"],
      "judgment_standard": "判断工作人员是否明确把确定的治疗结果、疗效或恢复结果承诺给当前患者，而不是仅说明可能性、条件或一般经验。",
      "trigger_conditions": ["保证性表达与治愈、治好、康复、恢复、痊愈或类似结果同时指向当前患者。"],
      "exclusion_conditions": ["不能保证", "无法保证", "不保证", "不敢保证", "不能承诺", "明确说明个体差异或结果不确定。"],
      "violation_examples": ["我保证你一定能治好。", "保证你术后视力能恢复到1.5。", "我们保证种植后20年不会掉。"],
      "compliant_examples": ["成功率在95%以上，但因个体差异，不能保证。", "大多数患者术后视力可以恢复到1.2-1.5。", "如果按医嘱护理，用20年问题不大，但不能保证。"],
      "fact_definition": "同一上下文中出现保证性表达和诊疗结果表达，并将结果指向当前患者。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "必要的前后文"],
      "required_external_facts": [],
      "indeterminate_boundary": "片段不足以判断说话人是在转述患者观点、引用问题还是本人承诺时，只形成候选发现。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "technical_validation",
      "source_basis": ["历史规则1.1", "legacy.rule-001.guarantee.direct"]
    },
    {
      "rule_code": "communication.guarantee.absolute",
      "legacy_rule_number": "1.2",
      "name": "绝对化诊疗效果表述",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条。"],
      "judgment_standard": "判断工作人员是否用一定、肯定、绝对、必然等绝对化语言描述诊疗效果、成功率、安全性或恢复结果；必须结合上下文，不能因为单个词出现就形成发现。",
      "trigger_conditions": ["绝对化或必然性表达与能、会等结果表达及治愈、治好、康复、恢复、痊愈等结果词形成同一语义。"],
      "exclusion_conditions": ["不能保证一定", "不一定能", "不一定会", "无法保证一定", "未必能", "不敢肯定", "患者提问而工作人员明确否定或限定。"],
      "violation_examples": ["你这个一定能治好。", "肯定会恢复的。", "绝对能看到1.5。"],
      "compliant_examples": ["有很大概率能治好，但不能说一定。", "大多数情况下会恢复，但也有个体差异。", "我们会尽力帮你恢复视力。"],
      "fact_definition": "同一上下文同时出现绝对化表达、结果可能性表达和诊疗结果表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "前后文"],
      "required_external_facts": [],
      "indeterminate_boundary": "绝对化词可能出现在否定、引用、患者提问或医生纠正中，不能据此自动定性。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "technical_validation",
      "source_basis": ["历史规则1.2", "legacy.rule-002.guarantee.implied"]
    },
    {
      "rule_code": "communication.guarantee.case",
      "legacy_rule_number": "1.3",
      "name": "以案例暗示当前患者结果",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条；反不正当竞争法关于引人误解宣传的相关规定。"],
      "judgment_standard": "判断工作人员是否把其他患者的成功案例、数量或结果直接推导为当前患者也会获得相同结果。",
      "trigger_conditions": ["成功案例或既往结果与“你也会、你也能、你也一样、没一个失败、全部成功、百分之百成功”等当前患者结果暗示同时出现。"],
      "exclusion_conditions": ["每个人情况不同", "因人而异", "不能保证", "不代表", "不一定", "仅客观介绍案例且没有推导当前患者结果。"],
      "violation_examples": ["上个月张女士做完现在1.5，你也会一样的。", "我们做过800例，没一个失败的，你放心。"],
      "compliant_examples": ["上个月张女士术后恢复得不错，但每个人情况不同。", "我们做过800例，成功率很高，但不能说100%成功。"],
      "fact_definition": "片段同时包含成功案例或既往结果引用，以及对当前患者结果的一致性暗示或绝对成功表述。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "可取得时的上下文"],
      "required_external_facts": [],
      "indeterminate_boundary": "引用案例本身不等于违规；无法判断案例真实性、患者是否主动询问或是否说明个体差异时，只作候选。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则1.3", "legacy.rule-003.guarantee.case"]
    },
    {
      "rule_code": "communication.guarantee.duration",
      "legacy_rule_number": "1.4",
      "name": "无条件承诺疗效维持时间",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条。"],
      "judgment_standard": "判断工作人员是否把疗效、器械效果或服务结果无条件承诺为长期、终身、永久或固定年限。",
      "trigger_conditions": ["一辈子、终身、永久、20年、几十年等时间表达与能用、有效、不会掉、不用换、一直用、维持等无条件结果表达同时出现。"],
      "exclusion_conditions": ["护理得当", "理论上", "可能", "因人而异", "需要复查", "不保证", "仅说明理论寿命而未承诺患者结果。"],
      "violation_examples": ["种植牙能用一辈子。", "保证20年不会掉。", "做完ICL终身有效。"],
      "compliant_examples": ["如果护理得当，种植牙可以用很多年，有患者用了20年以上。", "ICL晶体理论上可以长期使用，但也可能因某些原因需要取出。"],
      "fact_definition": "同一片段同时出现长期时长表达和无条件效果、使用或维持结果表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": [],
      "indeterminate_boundary": "客观经验、条件性说明或器械理论寿命不当然构成承诺，必须结合上下文复核。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则1.4", "legacy.rule-004.guarantee.duration"]
    },
    {
      "rule_code": "communication.misleading.exclusivity",
      "legacy_rule_number": "2.1",
      "name": "绝对化疗效、设备或方案排他宣传",
      "category": "诱导消费",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条；《医疗广告管理办法》关于保证性和引人误解宣传的规定。"],
      "judgment_standard": "判断咨询师是否把具体诊疗方案、技术、设备或机构表述为唯一、最好、最佳、独家或全国唯一。",
      "trigger_conditions": ["最好、最佳、唯一、独家、全国唯一等排他表达与方案、治疗、方法、技术、设备、医院或机构对象同时出现。"],
      "exclusion_conditions": ["之一", "各有优势", "未必", "不一定", "仅陈述客观配置或明确限定比较范围。"],
      "violation_examples": ["这是最好的治疗方案。", "唯一能治愈的方法。", "我们是全国唯一引进这个设备的。"],
      "compliant_examples": ["这是目前常用的治疗方案之一。", "这个方法效果不错，但也有其他选择。", "我们引进了这个设备，在本地区较为先进。"],
      "fact_definition": "同一片段同时出现绝对化、排他性表达和被推广的方案、技术、设备或机构对象。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "可取得时的宣传或设备事实"],
      "required_external_facts": [],
      "indeterminate_boundary": "医生基于病情进行医学比较不直接适用本规则；咨询师候选也不自动确认虚假宣传。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则2.1", "legacy.rule-005.misleading.exaggerate"]
    },
    {
      "rule_code": "communication.misleading.disparage",
      "legacy_rule_number": "2.2",
      "name": "无依据贬低其他方案或机构",
      "category": "诱导消费",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条。"],
      "judgment_standard": "判断咨询师是否把其他医院、医生、方案或传统方法与不行、骗人、太差、没用、落后等贬损表达组合，且没有给出可核验依据。",
      "trigger_conditions": ["其他医院、其他方案、传统方法、其他医生等对象与明确贬损表达同时出现。"],
      "exclusion_conditions": ["各有优势", "不代表", "不能一概而论", "要看情况", "存在可核验的比较依据并明确限定适用条件。"],
      "violation_examples": ["别的医院都不行，只有我们能做。", "传统方法效果差，都是骗人的。", "那家医院的设备太老了。"],
      "compliant_examples": ["我们在这方面有丰富经验，但其他医院也有各自的优势。", "传统方法也有效果，只是我们这个方法更先进一些。", "不同医院的设备配置不同，各有特点。"],
      "fact_definition": "片段同时出现可识别的其他机构、医生或方案对象，以及无依据的贬损表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "可取得时的比较依据"],
      "required_external_facts": ["比较对象的设备、技术或服务事实，视具体表达而定"],
      "indeterminate_boundary": "医生可能基于病情作医学比较；咨询师候选也需人工判断是否有事实依据。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则2.2", "历史规则6.1", "legacy.rule-006.misleading.degrade", "legacy.rule-017.other.degrade"]
    },
    {
      "rule_code": "communication.misleading.urgency",
      "legacy_rule_number": "2.3",
      "name": "非医学依据的成交紧迫施压",
      "category": "诱导消费",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条；价格和促销信息真实性相关要求。"],
      "judgment_standard": "判断时间、名额、涨价、活动或排队表达是否以不真实或不完整的外部事实推动患者立即成交。",
      "trigger_conditions": ["今天、现在、马上、只剩名额、明天涨价、下月排队等紧迫表达与优惠、活动、名额或预约同时出现。"],
      "exclusion_conditions": ["真实活动且信息完整", "真实预约紧张且可核验", "只是建议尽早预约而没有虚构后果。"],
      "violation_examples": ["今天不做，明天就涨价了。", "现在只剩3个名额了。", "这个月不做，下个月就要排队半年。"],
      "compliant_examples": ["我们目前有优惠活动，具体可以咨询前台。", "近期预约的患者比较多，建议您尽早决定。", "医生的档期比较满，建议提前预约。"],
      "fact_definition": "录音中的时间、名额、涨价或排队表达与实际活动、价格或预约事实不一致。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["活动规则", "名额或预约记录", "价格或有效期"],
      "indeterminate_boundary": "录音单独不能证明紧迫表达不真实或不当。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则2.3", "legacy.rule-007.misleading.urgency"]
    },
    {
      "rule_code": "communication.misleading.data_unverified",
      "legacy_rule_number": "2.4",
      "name": "无法核验的宣传数据",
      "category": "诱导消费",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条。"],
      "judgment_standard": "判断工作人员是否使用满意度、成功率、无事故、万例等数据，并将其作为可信结果或成交依据，但医院无法提供来源、统计口径或有效期。",
      "trigger_conditions": ["98%满意度、万例无事故、百分之百成功等具体数据与宣传或成交语境同时出现。"],
      "exclusion_conditions": ["有可核验来源、统计口径和有效期", "仅表达主观感受且没有伪装成统计数据。"],
      "violation_examples": ["我们的患者满意度98%。", "万例手术无一例事故。"],
      "compliant_examples": ["大多数患者对手术效果比较满意。", "我们非常重视手术安全，有完善的质控流程。"],
      "fact_definition": "沟通中使用统计或效果数据，但缺少可核验来源、口径或有效期。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["数据来源", "统计口径", "有效期", "必要时的审计或质控记录"],
      "indeterminate_boundary": "出现数字本身不等于虚假数据；没有外部资料时只能提示待核验。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则2.4", "legacy.rule-008.misleading.data"]
    },
    {
      "rule_code": "communication.fear.exaggeration",
      "legacy_rule_number": "3.1",
      "name": "夸大风险推动决策",
      "category": "制造焦虑",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["医疗风险告知和医疗宣传真实性相关要求。"],
      "judgment_standard": "判断工作人员是否通过夸大疾病严重程度、拖延后果或时间压力推动当前患者立即作出诊疗决定，而不是基于事实进行合理风险告知。",
      "trigger_conditions": ["很严重、非常危险、再不做就来不及了、拖不得等严重或紧迫表达指向当前患者决定。"],
      "exclusion_conditions": ["不用担心", "不必过度担心", "没有那么严重", "不严重", "有医学检查、病情和处理时限依据。"],
      "violation_examples": ["你这个很严重，再不做就瞎了。", "这个必须马上手术，否则会恶化。", "你这个拖不得，再拖就完了。"],
      "compliant_examples": ["您的白内障已到中期，建议尽快手术，以免影响日常生活。", "这个病情需要及时治疗，但也不用过度紧张。", "建议您尽早手术，但具体时间可以和医生商量。"],
      "fact_definition": "原始转写片段出现可能利用严重后果或时间压力推动决策的表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["涉及医学严重程度或时限时，应补充病历、检查或医学依据"],
      "indeterminate_boundary": "严重程度和处理时限需要结合患者病情、检查结果和医学依据；本规则只能提供候选线索。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "technical_validation",
      "source_basis": ["历史规则3.1", "legacy.rule-009.fear.severity"]
    },
    {
      "rule_code": "communication.fear.panic",
      "legacy_rule_number": "3.2",
      "name": "不做即发生绝对严重后果",
      "category": "制造焦虑",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["医疗风险告知和医疗宣传真实性相关要求。"],
      "judgment_standard": "判断工作人员是否把不做某项治疗直接关联失明、全掉光或其他绝对严重后果，并以此推动患者决定。",
      "trigger_conditions": ["不做、不治疗、不手术、不种牙、不矫正等表达与失明、全掉光、瞎了、恶化或严重后果直接关联。"],
      "exclusion_conditions": ["有可能", "定期检查", "因人而异", "医生评估", "需要检查", "明确表达风险概率和条件。"],
      "violation_examples": ["不种牙的话，其他牙齿也会松动，最后全掉光。", "近视不矫正，度数会越来越深，最后会失明。"],
      "compliant_examples": ["缺牙后，邻牙可能会移位，建议考虑种植修复。", "近视度数可能会加深，建议定期检查。"],
      "fact_definition": "同一片段把不做治疗或矫正与绝对严重后果直接关联。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["医生场景下的病历或检查事实", "必要时的医学依据"],
      "indeterminate_boundary": "医学风险说明可能合理，尤其医生场景必须结合病历和检查事实复核，系统不确认夸大病情。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则3.2", "legacy.rule-010.fear.panic"]
    },
    {
      "rule_code": "communication.fear.compare",
      "legacy_rule_number": "3.3",
      "name": "做与不做的夸张后果对比",
      "category": "制造焦虑",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["医疗风险告知和医疗宣传真实性相关要求。"],
      "judgment_standard": "判断工作人员是否把治疗后的绝对正面结果与不治疗后的绝对负面结果并列，以夸张对比推动当前患者选择。",
      "trigger_conditions": ["治疗后、做完等正向结果与不做、不治疗等负向结果同时出现，且两边都使用绝对化或极端结果。"],
      "exclusion_conditions": ["可以选择", "也可以", "个人选择", "因人而异", "客观说明不同方案的风险和收益。"],
      "violation_examples": ["做了你就能看得清清楚楚；不做你就要戴一辈子眼镜，还会越来越深。"],
      "compliant_examples": ["手术后视力会有改善，但也可以选择继续戴眼镜，这是您的个人选择。"],
      "fact_definition": "同一片段同时对治疗后和不治疗后的结果作绝对化正负对比。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["医生场景下的病历或检查事实", "涉及治疗效果时的医学依据"],
      "indeterminate_boundary": "治疗方案比较可能是必要告知，医生场景尤其需要医学事实复核。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则3.3", "legacy.rule-011.fear.compare"]
    },
    {
      "rule_code": "content.price.false_original",
      "legacy_rule_number": "4.1",
      "name": "虚构原价或虚假优惠",
      "category": "价格欺诈",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["《价格法》第十四条：不得虚构原价、虚假优惠折价。"],
      "judgment_standard": "判断内容宣称的原价、市场价或优惠是否与可核验的价格表、活动规则和生效记录不一致。",
      "trigger_conditions": ["内容先报高价再宣布大幅优惠，或使用市场价、原价、活动价作为购买依据。"],
      "exclusion_conditions": ["价格和活动有有效记录", "活动期限、适用条件和比较价格完整披露。"],
      "violation_examples": ["原价3万，现在活动价1.5万，但实际从未卖过3万。", "市场价5万，我们只要2万，但没有市场价依据。"],
      "compliant_examples": ["我们的价格是2万，目前有优惠活动。", "不同医院价格不同，我们的价格在XX元左右。"],
      "fact_definition": "内容宣称的原价、市场价或优惠与可核验价格和活动资料不一致。",
      "required_evidence": ["内容版本快照", "发布渠道和时间"],
      "required_external_facts": ["价格表", "活动规则", "价格生效记录"],
      "indeterminate_boundary": "文字中的原价和优惠不能单独证明价格虚假。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则4.1", "legacy.rule-012.price.fake_original"]
    },
    {
      "rule_code": "content.price.hidden_fee",
      "legacy_rule_number": "4.2",
      "name": "隐瞒费用构成",
      "category": "价格欺诈",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["《价格法》及价格信息明示相关要求。"],
      "judgment_standard": "判断内容报价是否遗漏应披露且会影响总价的费用、材料、检查、复查或适用条件。",
      "trigger_conditions": ["只展示单项低价，而项目实际还包含牙冠、骨粉、检查、复查或其他必要费用。"],
      "exclusion_conditions": ["已明确项目范围和费用构成", "已说明其他费用另算及预计总额或区间。"],
      "violation_examples": ["种植牙1万一颗，但不说还要加牙冠、骨粉等费用。", "ICL手术2万，但不说术前检查和术后复查费用。"],
      "compliant_examples": ["种植体费用1万，加上牙冠和其他费用，总计约1.5到2万。", "手术费用2万，术前检查和术后复查另算，总共约2.5万。"],
      "fact_definition": "内容中的项目报价遗漏会影响总价的费用构成或适用条件。",
      "required_evidence": ["内容版本快照", "价格文案所在位置"],
      "required_external_facts": ["项目费用构成", "价格表", "适用条件"],
      "indeterminate_boundary": "单一价格文案不能自动证明隐瞒费用。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则4.2", "legacy.rule-013.price.hidden_fee"]
    },
    {
      "rule_code": "communication.price.on_site_increase",
      "legacy_rule_number": "4.3",
      "name": "电话低价与到店报价不一致",
      "category": "价格欺诈",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《价格法》第十四条。"],
      "judgment_standard": "判断首次沟通报价与到店后的相同项目报价是否不一致，且不存在已告知的材料、项目或服务范围差异。",
      "trigger_conditions": ["电话或首次沟通报低价，到店后以材料、效果或其他理由引导到更高价格。"],
      "exclusion_conditions": ["项目或材料不同且已告知", "价格区间已完整说明", "到店报价变化有真实项目依据。"],
      "violation_examples": ["电话说种植牙5000一颗，到店后说5000是最便宜材料，建议用2万的。"],
      "compliant_examples": ["种植牙根据材料不同，价格从5000到2万不等，建议来院详细了解。"],
      "fact_definition": "首次沟通报价与到院后的相同项目报价不一致，且不存在可核验的材料、项目或服务范围差异。",
      "required_evidence": ["首次报价录音或记录", "到院报价记录", "相关对话时间"],
      "required_external_facts": ["首次报价", "到院报价", "项目价格表", "到院记录"],
      "indeterminate_boundary": "单段录音不能证明实际成交价格或费用构成。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则4.3", "legacy.rule-014.price.on_site"]
    },
    {
      "rule_code": "communication.scope.cross_department",
      "legacy_rule_number": "5.1",
      "name": "表达服务范围与执业资质不一致",
      "category": "超范围执业",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.doctor.outpatient"],
      "legal_basis": ["《执业医师法》第十四条。"],
      "judgment_standard": "判断人员在沟通中表达的服务能力是否与其可核验的执业范围、科室、排班或授权不一致。",
      "trigger_conditions": ["人员主动表示可以提供不属于其执业范围或科室范围的医疗服务。"],
      "exclusion_conditions": ["已转诊", "明确说明不在本人范围", "有有效授权和排班依据。"],
      "violation_examples": ["口腔科医生说我也会做双眼皮，来找我吧。", "眼科医生说我也能看牙，顺便给你看看。"],
      "compliant_examples": ["这个不在我的执业范围，我帮您联系眼科医生。", "这个需要口腔科医生来看，我给您转诊。"],
      "fact_definition": "人员表达的服务能力与其可核验的执业范围、科室或授权不一致。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["执业范围", "人员排班或科室", "实际服务项目", "授权记录"],
      "indeterminate_boundary": "录音不能自行证明超范围执业。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则5.1", "legacy.rule-015.scope.cross_department"]
    },
    {
      "rule_code": "communication.scope.untrained_technology",
      "legacy_rule_number": "5.2",
      "name": "表达使用新技术与培训授权不一致",
      "category": "超范围执业",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.doctor.outpatient"],
      "legal_basis": ["《执业医师法》及医疗技术准入、授权相关要求。"],
      "judgment_standard": "判断人员是否表达可以使用新技术或设备，但培训、授权或资格资料不能支持该表达。",
      "trigger_conditions": ["工作人员表示自己可以操作新技术、新设备或新项目。"],
      "exclusion_conditions": ["有效培训和授权齐备", "由具备资格人员实际服务", "明确表示由专门医生负责。"],
      "violation_examples": ["这个新技术我也能做，但实际没有培训或授权。"],
      "compliant_examples": ["这个新技术我们医院有，由专门的医生负责。"],
      "fact_definition": "人员表达可使用新技术或设备，但培训、授权或资格资料不能支持该表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["培训记录", "设备或技术授权", "人员资格"],
      "indeterminate_boundary": "录音不能自行证明未经培训或无授权。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则5.2", "legacy.rule-016.scope.untrained_tech"]
    },
    {
      "rule_code": "communication.other.peer_disparagement",
      "legacy_rule_number": "6.1",
      "name": "诋毁同行",
      "category": "其他",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条。"],
      "judgment_standard": "判断工作人员是否对其他医院、医生或同行作出无依据的贬损表达，并以此突出自身服务。",
      "trigger_conditions": ["明确指向其他医院或医生的贬低、否定、侮辱性表达。"],
      "exclusion_conditions": ["各有特点", "客观比较且有依据", "不代表", "不能一概而论"],
      "violation_examples": ["别的医院都不行，只有我们能做。", "XX医院的医生水平太差了。"],
      "compliant_examples": ["我们在这方面有丰富经验。", "不同医院各有特点。"],
      "fact_definition": "指向同行对象的贬损表达，且无法提供客观比较依据。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["比较依据，视具体表达而定"],
      "indeterminate_boundary": "该规则与“无依据贬低其他方案或机构”存在业务关联，但本最终版本保留原始规则身份；实现时可在展示层关联，不得重复制造两条发现。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则6.1", "legacy.rule-017.other.degrade"]
    },
    {
      "rule_code": "content.privacy.patient",
      "legacy_rule_number": "6.2",
      "name": "患者隐私或案例展示未获授权",
      "category": "其他",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["患者隐私、个人信息保护和医疗案例授权相关要求。"],
      "judgment_standard": "判断内容是否展示可识别患者身份、照片、影像或案例信息，但无法提供匹配的授权和脱敏依据。",
      "trigger_conditions": ["姓名、年龄、单位、照片、影像或其他可识别信息与患者案例展示同时出现。"],
      "exclusion_conditions": ["患者已授权", "已按传播范围完成脱敏", "内容使用完全虚构或不可识别案例。"],
      "violation_examples": ["李女士，35岁，XX公司职员，上周在我们这里做了手术。", "展示未打码的患者照片。"],
      "compliant_examples": ["有位患者上周在我们这里做了相关治疗。", "展示患者照片并完成面部打码。"],
      "fact_definition": "内容展示可识别的患者身份、影像或案例信息，但无法提供匹配的授权和脱敏依据。",
      "required_evidence": ["内容版本快照", "图片或视频帧", "发布渠道"],
      "required_external_facts": ["患者授权", "脱敏范围", "传播渠道"],
      "indeterminate_boundary": "内容出现案例或照片不自动证明未经授权。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则6.2", "legacy.rule-018.other.privacy"]
    },
    {
      "rule_code": "content.honor.unverified",
      "legacy_rule_number": "6.3",
      "name": "无法核验的医院或人员荣誉资质宣传",
      "category": "其他",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["医疗机构和医务人员资质、荣誉宣传真实性相关要求。"],
      "judgment_standard": "判断内容宣称的医院等级、人员资质或荣誉称号是否有有效证明材料、医院授权和有效期支持。",
      "trigger_conditions": ["三甲医院、医学会会员、权威专家、荣誉称号或类似资质宣传无法关联有效证明。"],
      "exclusion_conditions": ["有权威证明", "医院授权有效", "资质或荣誉处于有效期内。"],
      "violation_examples": ["我们是三甲医院，但实际不是。", "我们医生是中华医学会会员，但实际不是。"],
      "compliant_examples": ["如实告知医院等级和医生资质。"],
      "fact_definition": "内容宣称的医院等级、人员资质或荣誉无法由有效证明材料支持。",
      "required_evidence": ["内容版本快照", "宣传文字或图片位置"],
      "required_external_facts": ["资质或荣誉证明", "医院授权", "有效期"],
      "indeterminate_boundary": "内容出现资质或荣誉称号不自动证明虚构。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则6.3", "legacy.rule-019.other.honor_fake"]
    }
  ],
  "migration_notes": {
    "from_worker_baseline": "Worker 当前的 communication.short_recording/20260906.1 只有 direct、absolute、fear.exaggeration 三条规则，属于最小可执行占位基线，不是本最终完整版。",
    "from_historical_sql": "历史 SQL 的 20260904.1 结构化规则卡提供了执行字段和边界，但把历史规则2.2与6.1合并；本文件为保留完整业务语义，将其拆回两个规则身份，并明确它们的关联。",
    "canonical_rule_source": "以后规则讨论、提示词设计、数据库迁移和测试用例均以本文件为基础；历史 Markdown、历史 SQL 和 Worker catalog 只作为归档，不再作为规则定义来源。",
    "implementation_warning": "本文件是规则规范和迁移基准，不代表所有规则已经进入当前运行 API。规则进入数据库和运行规则集前，必须依据 status、required_external_facts 和 validation_status 执行对应的发布审核。"
  }
}
$canonical$::jsonb AS document
),
catalog AS (
  INSERT INTO guard_rule_catalog_versions (version, schema_version, status, title, purpose, execution_policy, field_definitions, migration_notes, definition)
  SELECT document->>'version', document->>'schema_version', document->>'status', document->>'title', document->>'purpose', COALESCE(document->'execution_policy', '{}'::jsonb), COALESCE(document->'field_definitions', '{}'::jsonb), COALESCE(document->'migration_notes', '{}'::jsonb), document
  FROM canonical
  ON CONFLICT (version) DO UPDATE SET schema_version = EXCLUDED.schema_version, status = EXCLUDED.status, title = EXCLUDED.title, purpose = EXCLUDED.purpose, execution_policy = EXCLUDED.execution_policy, field_definitions = EXCLUDED.field_definitions, migration_notes = EXCLUDED.migration_notes, definition = EXCLUDED.definition
  RETURNING id, version
)
INSERT INTO guard_rule_versions (
  catalog_id, tenant_id, rule_code, legacy_rule_number, rule_name, category, subject, source_kind, version, status,
  applicable_rule_sets, legal_basis, judgment_standard, trigger_conditions, exclusion_conditions, violation_examples, compliant_examples,
  fact_definition, required_evidence, required_external_facts, indeterminate_boundary, output_type, review_priority, validation_status, source_basis, definition, published_at
)
SELECT catalog.id, NULL, rule->>'rule_code', COALESCE(rule->>'legacy_rule_number', ''), COALESCE(rule->>'name', ''), COALESCE(rule->>'category', ''), rule->>'subject', 'platform', canonical.document->>'version', rule->>'status',
  COALESCE(rule->'applicable_rule_sets', '[]'::jsonb), COALESCE(rule->'legal_basis', '[]'::jsonb), COALESCE(rule->>'judgment_standard', ''), COALESCE(rule->'trigger_conditions', '[]'::jsonb), COALESCE(rule->'exclusion_conditions', '[]'::jsonb), COALESCE(rule->'violation_examples', '[]'::jsonb), COALESCE(rule->'compliant_examples', '[]'::jsonb), COALESCE(rule->>'fact_definition', ''), COALESCE(rule->'required_evidence', '[]'::jsonb), COALESCE(rule->'required_external_facts', '[]'::jsonb), COALESCE(rule->>'indeterminate_boundary', ''), COALESCE(rule->>'output_type', ''), COALESCE(rule->>'review_priority', ''), COALESCE(rule->>'validation_status', ''), COALESCE(rule->'source_basis', '[]'::jsonb), rule, CASE WHEN rule->>'status' = 'published' THEN NOW() ELSE NULL END
FROM canonical
CROSS JOIN catalog
CROSS JOIN LATERAL jsonb_array_elements(canonical.document->'rules') AS rule
ON CONFLICT DO NOTHING;

WITH canonical AS (
  SELECT 
$canonical$
{
  "schema_version": "1.0",
  "status": "canonical_current_baseline",
  "title": "合规卫士沟通与内容合规规则集",
  "version": "20260911.1",
  "purpose": "本文件是合规卫士当前规则讨论和后续实现的唯一基础。它自包含保存规则定义、业务说明、适用范围、判断边界和规则集成员关系，后续不需要回看历史规则文档或历史迁移 SQL。",
  "execution_policy": {
    "system_role": "合规引擎只发现需要医院查看的具体问题，不自动确认违规、不定责、不处罚。",
    "finding_granularity": "一次输入资料与一条规则最多形成一条发现；同一输入同一规则的多处证据合并到一条发现；同一输入不同规则分别形成发现；不同输入不得合并。",
    "llm_policy": "规则为大模型提供检查范围、判断标准、例外和证据要求；最终结论由医院复核。",
    "status_policy": "published 表示已进入对应规则集；draft 表示定义已保留但当前不应仅凭现有输入自动产生正式待核查发现。",
    "source_policy": "平台规则和医院本地规则分开管理；本院规则可以补充或收严平台规则，不能静默放宽平台底线。"
  },
  "field_definitions": {
    "rule_code": "规则的稳定编码。",
    "legacy_rule_number": "历史业务规则编号，仅用于追溯，不改变当前规则身份。",
    "subject": "规则处理的资料类型：communication 或 content。",
    "applicable_rule_sets": "规则进入哪些场景规则集。",
    "status": "当前发布状态。published 进入规则集，draft 只保留定义和待补资料要求。",
    "judgment_standard": "大模型和复核人员判断时必须回答的业务问题。",
    "trigger_conditions": "值得检查的表述或事实组合，不等于自动确认违规。",
    "exclusion_conditions": "出现这些条件时，不应仅凭本规则形成肯定性发现，或应降低为需要补充资料的候选。",
    "required_evidence": "发现和人工复核应尽量提供的证据。",
    "required_external_facts": "录音或内容本身之外必须补充的事实。",
    "indeterminate_boundary": "仅凭当前输入无法确定的边界。",
    "validation_status": "当前规则的验证状态。"
  },
  "rule_sets": [
    {
      "code": "communication.doctor.outpatient",
      "name": "医生门诊沟通规则集",
      "subject": "communication",
      "role_codes": ["doctor", "doctor_assistant"],
      "source_types": ["recording"],
      "status": "published",
      "included_rule_codes": [
        "communication.guarantee.direct",
        "communication.guarantee.absolute",
        "communication.guarantee.case",
        "communication.guarantee.duration",
        "communication.misleading.data_unverified",
        "communication.fear.exaggeration",
        "communication.fear.panic",
        "communication.fear.compare",
        "communication.scope.cross_department",
        "communication.scope.untrained_technology"
      ],
      "notes": "涉及价格成交、内容发布和必须核验外部事实的规则暂不作为仅凭医生录音自动检查的正式规则。"
    },
    {
      "code": "communication.consultant.consultation",
      "name": "咨询师咨询成交沟通规则集",
      "subject": "communication",
      "role_codes": ["consultant"],
      "source_types": ["recording"],
      "status": "published",
      "included_rule_codes": [
        "communication.guarantee.direct",
        "communication.guarantee.absolute",
        "communication.guarantee.case",
        "communication.guarantee.duration",
        "communication.misleading.exclusivity",
        "communication.misleading.disparage",
        "communication.misleading.urgency",
        "communication.misleading.data_unverified",
        "communication.fear.exaggeration",
        "communication.fear.panic",
        "communication.fear.compare",
        "communication.price.on_site_increase"
      ],
      "notes": "需要价格、活动或预约事实的规则保留为候选规则；没有外部事实时不得自动认定。"
    },
    {
      "code": "content.pre_publish",
      "name": "宣传内容发布前检查规则集",
      "subject": "content",
      "role_codes": [],
      "source_types": ["content_item", "script", "copy", "image_text"],
      "status": "draft",
      "included_rule_codes": [
        "content.price.false_original",
        "content.price.hidden_fee",
        "content.data.unverified",
        "content.privacy.patient",
        "content.honor.unverified"
      ],
      "notes": "内容中心正式接入和价格、授权、资质资料接入后发布。"
    }
  ],
  "rules": [
    {
      "rule_code": "communication.guarantee.direct",
      "legacy_rule_number": "1.1",
      "name": "直接保证诊疗结果",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条：不得对诊疗效果作出保证性承诺。"],
      "judgment_standard": "判断工作人员是否明确把确定的治疗结果、疗效或恢复结果承诺给当前患者，而不是仅说明可能性、条件或一般经验。",
      "trigger_conditions": ["保证性表达与治愈、治好、康复、恢复、痊愈或类似结果同时指向当前患者。"],
      "exclusion_conditions": ["不能保证", "无法保证", "不保证", "不敢保证", "不能承诺", "明确说明个体差异或结果不确定。"],
      "violation_examples": ["我保证你一定能治好。", "保证你术后视力能恢复到1.5。", "我们保证种植后20年不会掉。"],
      "compliant_examples": ["成功率在95%以上，但因个体差异，不能保证。", "大多数患者术后视力可以恢复到1.2-1.5。", "如果按医嘱护理，用20年问题不大，但不能保证。"],
      "fact_definition": "同一上下文中出现保证性表达和诊疗结果表达，并将结果指向当前患者。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "必要的前后文"],
      "required_external_facts": [],
      "indeterminate_boundary": "片段不足以判断说话人是在转述患者观点、引用问题还是本人承诺时，只形成候选发现。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "technical_validation",
      "source_basis": ["历史规则1.1", "legacy.rule-001.guarantee.direct"]
    },
    {
      "rule_code": "communication.guarantee.absolute",
      "legacy_rule_number": "1.2",
      "name": "绝对化诊疗效果表述",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条。"],
      "judgment_standard": "判断工作人员是否用一定、肯定、绝对、必然等绝对化语言描述诊疗效果、成功率、安全性或恢复结果；必须结合上下文，不能因为单个词出现就形成发现。",
      "trigger_conditions": ["绝对化或必然性表达与能、会等结果表达及治愈、治好、康复、恢复、痊愈等结果词形成同一语义。"],
      "exclusion_conditions": ["不能保证一定", "不一定能", "不一定会", "无法保证一定", "未必能", "不敢肯定", "患者提问而工作人员明确否定或限定。"],
      "violation_examples": ["你这个一定能治好。", "肯定会恢复的。", "绝对能看到1.5。"],
      "compliant_examples": ["有很大概率能治好，但不能说一定。", "大多数情况下会恢复，但也有个体差异。", "我们会尽力帮你恢复视力。"],
      "fact_definition": "同一上下文同时出现绝对化表达、结果可能性表达和诊疗结果表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "前后文"],
      "required_external_facts": [],
      "indeterminate_boundary": "绝对化词可能出现在否定、引用、患者提问或医生纠正中，不能据此自动定性。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "technical_validation",
      "source_basis": ["历史规则1.2", "legacy.rule-002.guarantee.implied"]
    },
    {
      "rule_code": "communication.guarantee.case",
      "legacy_rule_number": "1.3",
      "name": "以案例暗示当前患者结果",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条；反不正当竞争法关于引人误解宣传的相关规定。"],
      "judgment_standard": "判断工作人员是否把其他患者的成功案例、数量或结果直接推导为当前患者也会获得相同结果。",
      "trigger_conditions": ["成功案例或既往结果与“你也会、你也能、你也一样、没一个失败、全部成功、百分之百成功”等当前患者结果暗示同时出现。"],
      "exclusion_conditions": ["每个人情况不同", "因人而异", "不能保证", "不代表", "不一定", "仅客观介绍案例且没有推导当前患者结果。"],
      "violation_examples": ["上个月张女士做完现在1.5，你也会一样的。", "我们做过800例，没一个失败的，你放心。"],
      "compliant_examples": ["上个月张女士术后恢复得不错，但每个人情况不同。", "我们做过800例，成功率很高，但不能说100%成功。"],
      "fact_definition": "片段同时包含成功案例或既往结果引用，以及对当前患者结果的一致性暗示或绝对成功表述。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "可取得时的上下文"],
      "required_external_facts": [],
      "indeterminate_boundary": "引用案例本身不等于违规；无法判断案例真实性、患者是否主动询问或是否说明个体差异时，只作候选。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则1.3", "legacy.rule-003.guarantee.case"]
    },
    {
      "rule_code": "communication.guarantee.duration",
      "legacy_rule_number": "1.4",
      "name": "无条件承诺疗效维持时间",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条。"],
      "judgment_standard": "判断工作人员是否把疗效、器械效果或服务结果无条件承诺为长期、终身、永久或固定年限。",
      "trigger_conditions": ["一辈子、终身、永久、20年、几十年等时间表达与能用、有效、不会掉、不用换、一直用、维持等无条件结果表达同时出现。"],
      "exclusion_conditions": ["护理得当", "理论上", "可能", "因人而异", "需要复查", "不保证", "仅说明理论寿命而未承诺患者结果。"],
      "violation_examples": ["种植牙能用一辈子。", "保证20年不会掉。", "做完ICL终身有效。"],
      "compliant_examples": ["如果护理得当，种植牙可以用很多年，有患者用了20年以上。", "ICL晶体理论上可以长期使用，但也可能因某些原因需要取出。"],
      "fact_definition": "同一片段同时出现长期时长表达和无条件效果、使用或维持结果表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": [],
      "indeterminate_boundary": "客观经验、条件性说明或器械理论寿命不当然构成承诺，必须结合上下文复核。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则1.4", "legacy.rule-004.guarantee.duration"]
    },
    {
      "rule_code": "communication.misleading.exclusivity",
      "legacy_rule_number": "2.1",
      "name": "绝对化疗效、设备或方案排他宣传",
      "category": "诱导消费",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条；《医疗广告管理办法》关于保证性和引人误解宣传的规定。"],
      "judgment_standard": "判断咨询师是否把具体诊疗方案、技术、设备或机构表述为唯一、最好、最佳、独家或全国唯一。",
      "trigger_conditions": ["最好、最佳、唯一、独家、全国唯一等排他表达与方案、治疗、方法、技术、设备、医院或机构对象同时出现。"],
      "exclusion_conditions": ["之一", "各有优势", "未必", "不一定", "仅陈述客观配置或明确限定比较范围。"],
      "violation_examples": ["这是最好的治疗方案。", "唯一能治愈的方法。", "我们是全国唯一引进这个设备的。"],
      "compliant_examples": ["这是目前常用的治疗方案之一。", "这个方法效果不错，但也有其他选择。", "我们引进了这个设备，在本地区较为先进。"],
      "fact_definition": "同一片段同时出现绝对化、排他性表达和被推广的方案、技术、设备或机构对象。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "可取得时的宣传或设备事实"],
      "required_external_facts": [],
      "indeterminate_boundary": "医生基于病情进行医学比较不直接适用本规则；咨询师候选也不自动确认虚假宣传。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则2.1", "legacy.rule-005.misleading.exaggerate"]
    },
    {
      "rule_code": "communication.misleading.disparage",
      "legacy_rule_number": "2.2",
      "name": "无依据贬低其他方案或机构",
      "category": "诱导消费",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条。"],
      "judgment_standard": "判断咨询师是否把其他医院、医生、方案或传统方法与不行、骗人、太差、没用、落后等贬损表达组合，且没有给出可核验依据。",
      "trigger_conditions": ["其他医院、其他方案、传统方法、其他医生等对象与明确贬损表达同时出现。"],
      "exclusion_conditions": ["各有优势", "不代表", "不能一概而论", "要看情况", "存在可核验的比较依据并明确限定适用条件。"],
      "violation_examples": ["别的医院都不行，只有我们能做。", "传统方法效果差，都是骗人的。", "那家医院的设备太老了。"],
      "compliant_examples": ["我们在这方面有丰富经验，但其他医院也有各自的优势。", "传统方法也有效果，只是我们这个方法更先进一些。", "不同医院的设备配置不同，各有特点。"],
      "fact_definition": "片段同时出现可识别的其他机构、医生或方案对象，以及无依据的贬损表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "可取得时的比较依据"],
      "required_external_facts": ["比较对象的设备、技术或服务事实，视具体表达而定"],
      "indeterminate_boundary": "医生可能基于病情作医学比较；咨询师候选也需人工判断是否有事实依据。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则2.2", "历史规则6.1", "legacy.rule-006.misleading.degrade", "legacy.rule-017.other.degrade"]
    },
    {
      "rule_code": "communication.misleading.urgency",
      "legacy_rule_number": "2.3",
      "name": "非医学依据的成交紧迫施压",
      "category": "诱导消费",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条；价格和促销信息真实性相关要求。"],
      "judgment_standard": "判断时间、名额、涨价、活动或排队表达是否以不真实或不完整的外部事实推动患者立即成交。",
      "trigger_conditions": ["今天、现在、马上、只剩名额、明天涨价、下月排队等紧迫表达与优惠、活动、名额或预约同时出现。"],
      "exclusion_conditions": ["真实活动且信息完整", "真实预约紧张且可核验", "只是建议尽早预约而没有虚构后果。"],
      "violation_examples": ["今天不做，明天就涨价了。", "现在只剩3个名额了。", "这个月不做，下个月就要排队半年。"],
      "compliant_examples": ["我们目前有优惠活动，具体可以咨询前台。", "近期预约的患者比较多，建议您尽早决定。", "医生的档期比较满，建议提前预约。"],
      "fact_definition": "录音中的时间、名额、涨价或排队表达与实际活动、价格或预约事实不一致。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["活动规则", "名额或预约记录", "价格或有效期"],
      "indeterminate_boundary": "录音单独不能证明紧迫表达不真实或不当。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则2.3", "legacy.rule-007.misleading.urgency"]
    },
    {
      "rule_code": "communication.misleading.data_unverified",
      "legacy_rule_number": "2.4",
      "name": "无法核验的宣传数据",
      "category": "诱导消费",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条。"],
      "judgment_standard": "判断工作人员是否使用满意度、成功率、无事故、万例等数据，并将其作为可信结果或成交依据，但医院无法提供来源、统计口径或有效期。",
      "trigger_conditions": ["98%满意度、万例无事故、百分之百成功等具体数据与宣传或成交语境同时出现。"],
      "exclusion_conditions": ["有可核验来源、统计口径和有效期", "仅表达主观感受且没有伪装成统计数据。"],
      "violation_examples": ["我们的患者满意度98%。", "万例手术无一例事故。"],
      "compliant_examples": ["大多数患者对手术效果比较满意。", "我们非常重视手术安全，有完善的质控流程。"],
      "fact_definition": "沟通中使用统计或效果数据，但缺少可核验来源、口径或有效期。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["数据来源", "统计口径", "有效期", "必要时的审计或质控记录"],
      "indeterminate_boundary": "出现数字本身不等于虚假数据；没有外部资料时只能提示待核验。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则2.4", "legacy.rule-008.misleading.data"]
    },
    {
      "rule_code": "communication.fear.exaggeration",
      "legacy_rule_number": "3.1",
      "name": "夸大风险推动决策",
      "category": "制造焦虑",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["医疗风险告知和医疗宣传真实性相关要求。"],
      "judgment_standard": "判断工作人员是否通过夸大疾病严重程度、拖延后果或时间压力推动当前患者立即作出诊疗决定，而不是基于事实进行合理风险告知。",
      "trigger_conditions": ["很严重、非常危险、再不做就来不及了、拖不得等严重或紧迫表达指向当前患者决定。"],
      "exclusion_conditions": ["不用担心", "不必过度担心", "没有那么严重", "不严重", "有医学检查、病情和处理时限依据。"],
      "violation_examples": ["你这个很严重，再不做就瞎了。", "这个必须马上手术，否则会恶化。", "你这个拖不得，再拖就完了。"],
      "compliant_examples": ["您的白内障已到中期，建议尽快手术，以免影响日常生活。", "这个病情需要及时治疗，但也不用过度紧张。", "建议您尽早手术，但具体时间可以和医生商量。"],
      "fact_definition": "原始转写片段出现可能利用严重后果或时间压力推动决策的表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["涉及医学严重程度或时限时，应补充病历、检查或医学依据"],
      "indeterminate_boundary": "严重程度和处理时限需要结合患者病情、检查结果和医学依据；本规则只能提供候选线索。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "technical_validation",
      "source_basis": ["历史规则3.1", "legacy.rule-009.fear.severity"]
    },
    {
      "rule_code": "communication.fear.panic",
      "legacy_rule_number": "3.2",
      "name": "不做即发生绝对严重后果",
      "category": "制造焦虑",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["医疗风险告知和医疗宣传真实性相关要求。"],
      "judgment_standard": "判断工作人员是否把不做某项治疗直接关联失明、全掉光或其他绝对严重后果，并以此推动患者决定。",
      "trigger_conditions": ["不做、不治疗、不手术、不种牙、不矫正等表达与失明、全掉光、瞎了、恶化或严重后果直接关联。"],
      "exclusion_conditions": ["有可能", "定期检查", "因人而异", "医生评估", "需要检查", "明确表达风险概率和条件。"],
      "violation_examples": ["不种牙的话，其他牙齿也会松动，最后全掉光。", "近视不矫正，度数会越来越深，最后会失明。"],
      "compliant_examples": ["缺牙后，邻牙可能会移位，建议考虑种植修复。", "近视度数可能会加深，建议定期检查。"],
      "fact_definition": "同一片段把不做治疗或矫正与绝对严重后果直接关联。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["医生场景下的病历或检查事实", "必要时的医学依据"],
      "indeterminate_boundary": "医学风险说明可能合理，尤其医生场景必须结合病历和检查事实复核，系统不确认夸大病情。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则3.2", "legacy.rule-010.fear.panic"]
    },
    {
      "rule_code": "communication.fear.compare",
      "legacy_rule_number": "3.3",
      "name": "做与不做的夸张后果对比",
      "category": "制造焦虑",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["医疗风险告知和医疗宣传真实性相关要求。"],
      "judgment_standard": "判断工作人员是否把治疗后的绝对正面结果与不治疗后的绝对负面结果并列，以夸张对比推动当前患者选择。",
      "trigger_conditions": ["治疗后、做完等正向结果与不做、不治疗等负向结果同时出现，且两边都使用绝对化或极端结果。"],
      "exclusion_conditions": ["可以选择", "也可以", "个人选择", "因人而异", "客观说明不同方案的风险和收益。"],
      "violation_examples": ["做了你就能看得清清楚楚；不做你就要戴一辈子眼镜，还会越来越深。"],
      "compliant_examples": ["手术后视力会有改善，但也可以选择继续戴眼镜，这是您的个人选择。"],
      "fact_definition": "同一片段同时对治疗后和不治疗后的结果作绝对化正负对比。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["医生场景下的病历或检查事实", "涉及治疗效果时的医学依据"],
      "indeterminate_boundary": "治疗方案比较可能是必要告知，医生场景尤其需要医学事实复核。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则3.3", "legacy.rule-011.fear.compare"]
    },
    {
      "rule_code": "content.price.false_original",
      "legacy_rule_number": "4.1",
      "name": "虚构原价或虚假优惠",
      "category": "价格欺诈",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["《价格法》第十四条：不得虚构原价、虚假优惠折价。"],
      "judgment_standard": "判断内容宣称的原价、市场价或优惠是否与可核验的价格表、活动规则和生效记录不一致。",
      "trigger_conditions": ["内容先报高价再宣布大幅优惠，或使用市场价、原价、活动价作为购买依据。"],
      "exclusion_conditions": ["价格和活动有有效记录", "活动期限、适用条件和比较价格完整披露。"],
      "violation_examples": ["原价3万，现在活动价1.5万，但实际从未卖过3万。", "市场价5万，我们只要2万，但没有市场价依据。"],
      "compliant_examples": ["我们的价格是2万，目前有优惠活动。", "不同医院价格不同，我们的价格在XX元左右。"],
      "fact_definition": "内容宣称的原价、市场价或优惠与可核验价格和活动资料不一致。",
      "required_evidence": ["内容版本快照", "发布渠道和时间"],
      "required_external_facts": ["价格表", "活动规则", "价格生效记录"],
      "indeterminate_boundary": "文字中的原价和优惠不能单独证明价格虚假。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则4.1", "legacy.rule-012.price.fake_original"]
    },
    {
      "rule_code": "content.price.hidden_fee",
      "legacy_rule_number": "4.2",
      "name": "隐瞒费用构成",
      "category": "价格欺诈",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["《价格法》及价格信息明示相关要求。"],
      "judgment_standard": "判断内容报价是否遗漏应披露且会影响总价的费用、材料、检查、复查或适用条件。",
      "trigger_conditions": ["只展示单项低价，而项目实际还包含牙冠、骨粉、检查、复查或其他必要费用。"],
      "exclusion_conditions": ["已明确项目范围和费用构成", "已说明其他费用另算及预计总额或区间。"],
      "violation_examples": ["种植牙1万一颗，但不说还要加牙冠、骨粉等费用。", "ICL手术2万，但不说术前检查和术后复查费用。"],
      "compliant_examples": ["种植体费用1万，加上牙冠和其他费用，总计约1.5到2万。", "手术费用2万，术前检查和术后复查另算，总共约2.5万。"],
      "fact_definition": "内容中的项目报价遗漏会影响总价的费用构成或适用条件。",
      "required_evidence": ["内容版本快照", "价格文案所在位置"],
      "required_external_facts": ["项目费用构成", "价格表", "适用条件"],
      "indeterminate_boundary": "单一价格文案不能自动证明隐瞒费用。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则4.2", "legacy.rule-013.price.hidden_fee"]
    },
    {
      "rule_code": "communication.price.on_site_increase",
      "legacy_rule_number": "4.3",
      "name": "电话低价与到店报价不一致",
      "category": "价格欺诈",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《价格法》第十四条。"],
      "judgment_standard": "判断首次沟通报价与到店后的相同项目报价是否不一致，且不存在已告知的材料、项目或服务范围差异。",
      "trigger_conditions": ["电话或首次沟通报低价，到店后以材料、效果或其他理由引导到更高价格。"],
      "exclusion_conditions": ["项目或材料不同且已告知", "价格区间已完整说明", "到店报价变化有真实项目依据。"],
      "violation_examples": ["电话说种植牙5000一颗，到店后说5000是最便宜材料，建议用2万的。"],
      "compliant_examples": ["种植牙根据材料不同，价格从5000到2万不等，建议来院详细了解。"],
      "fact_definition": "首次沟通报价与到院后的相同项目报价不一致，且不存在可核验的材料、项目或服务范围差异。",
      "required_evidence": ["首次报价录音或记录", "到院报价记录", "相关对话时间"],
      "required_external_facts": ["首次报价", "到院报价", "项目价格表", "到院记录"],
      "indeterminate_boundary": "单段录音不能证明实际成交价格或费用构成。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则4.3", "legacy.rule-014.price.on_site"]
    },
    {
      "rule_code": "communication.scope.cross_department",
      "legacy_rule_number": "5.1",
      "name": "表达服务范围与执业资质不一致",
      "category": "超范围执业",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.doctor.outpatient"],
      "legal_basis": ["《执业医师法》第十四条。"],
      "judgment_standard": "判断人员在沟通中表达的服务能力是否与其可核验的执业范围、科室、排班或授权不一致。",
      "trigger_conditions": ["人员主动表示可以提供不属于其执业范围或科室范围的医疗服务。"],
      "exclusion_conditions": ["已转诊", "明确说明不在本人范围", "有有效授权和排班依据。"],
      "violation_examples": ["口腔科医生说我也会做双眼皮，来找我吧。", "眼科医生说我也能看牙，顺便给你看看。"],
      "compliant_examples": ["这个不在我的执业范围，我帮您联系眼科医生。", "这个需要口腔科医生来看，我给您转诊。"],
      "fact_definition": "人员表达的服务能力与其可核验的执业范围、科室或授权不一致。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["执业范围", "人员排班或科室", "实际服务项目", "授权记录"],
      "indeterminate_boundary": "录音不能自行证明超范围执业。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则5.1", "legacy.rule-015.scope.cross_department"]
    },
    {
      "rule_code": "communication.scope.untrained_technology",
      "legacy_rule_number": "5.2",
      "name": "表达使用新技术与培训授权不一致",
      "category": "超范围执业",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.doctor.outpatient"],
      "legal_basis": ["《执业医师法》及医疗技术准入、授权相关要求。"],
      "judgment_standard": "判断人员是否表达可以使用新技术或设备，但培训、授权或资格资料不能支持该表达。",
      "trigger_conditions": ["工作人员表示自己可以操作新技术、新设备或新项目。"],
      "exclusion_conditions": ["有效培训和授权齐备", "由具备资格人员实际服务", "明确表示由专门医生负责。"],
      "violation_examples": ["这个新技术我也能做，但实际没有培训或授权。"],
      "compliant_examples": ["这个新技术我们医院有，由专门的医生负责。"],
      "fact_definition": "人员表达可使用新技术或设备，但培训、授权或资格资料不能支持该表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["培训记录", "设备或技术授权", "人员资格"],
      "indeterminate_boundary": "录音不能自行证明未经培训或无授权。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则5.2", "legacy.rule-016.scope.untrained_tech"]
    },
    {
      "rule_code": "communication.other.peer_disparagement",
      "legacy_rule_number": "6.1",
      "name": "诋毁同行",
      "category": "其他",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条。"],
      "judgment_standard": "判断工作人员是否对其他医院、医生或同行作出无依据的贬损表达，并以此突出自身服务。",
      "trigger_conditions": ["明确指向其他医院或医生的贬低、否定、侮辱性表达。"],
      "exclusion_conditions": ["各有特点", "客观比较且有依据", "不代表", "不能一概而论"],
      "violation_examples": ["别的医院都不行，只有我们能做。", "XX医院的医生水平太差了。"],
      "compliant_examples": ["我们在这方面有丰富经验。", "不同医院各有特点。"],
      "fact_definition": "指向同行对象的贬损表达，且无法提供客观比较依据。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["比较依据，视具体表达而定"],
      "indeterminate_boundary": "该规则与“无依据贬低其他方案或机构”存在业务关联，但本最终版本保留原始规则身份；实现时可在展示层关联，不得重复制造两条发现。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则6.1", "legacy.rule-017.other.degrade"]
    },
    {
      "rule_code": "content.privacy.patient",
      "legacy_rule_number": "6.2",
      "name": "患者隐私或案例展示未获授权",
      "category": "其他",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["患者隐私、个人信息保护和医疗案例授权相关要求。"],
      "judgment_standard": "判断内容是否展示可识别患者身份、照片、影像或案例信息，但无法提供匹配的授权和脱敏依据。",
      "trigger_conditions": ["姓名、年龄、单位、照片、影像或其他可识别信息与患者案例展示同时出现。"],
      "exclusion_conditions": ["患者已授权", "已按传播范围完成脱敏", "内容使用完全虚构或不可识别案例。"],
      "violation_examples": ["李女士，35岁，XX公司职员，上周在我们这里做了手术。", "展示未打码的患者照片。"],
      "compliant_examples": ["有位患者上周在我们这里做了相关治疗。", "展示患者照片并完成面部打码。"],
      "fact_definition": "内容展示可识别的患者身份、影像或案例信息，但无法提供匹配的授权和脱敏依据。",
      "required_evidence": ["内容版本快照", "图片或视频帧", "发布渠道"],
      "required_external_facts": ["患者授权", "脱敏范围", "传播渠道"],
      "indeterminate_boundary": "内容出现案例或照片不自动证明未经授权。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则6.2", "legacy.rule-018.other.privacy"]
    },
    {
      "rule_code": "content.honor.unverified",
      "legacy_rule_number": "6.3",
      "name": "无法核验的医院或人员荣誉资质宣传",
      "category": "其他",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["医疗机构和医务人员资质、荣誉宣传真实性相关要求。"],
      "judgment_standard": "判断内容宣称的医院等级、人员资质或荣誉称号是否有有效证明材料、医院授权和有效期支持。",
      "trigger_conditions": ["三甲医院、医学会会员、权威专家、荣誉称号或类似资质宣传无法关联有效证明。"],
      "exclusion_conditions": ["有权威证明", "医院授权有效", "资质或荣誉处于有效期内。"],
      "violation_examples": ["我们是三甲医院，但实际不是。", "我们医生是中华医学会会员，但实际不是。"],
      "compliant_examples": ["如实告知医院等级和医生资质。"],
      "fact_definition": "内容宣称的医院等级、人员资质或荣誉无法由有效证明材料支持。",
      "required_evidence": ["内容版本快照", "宣传文字或图片位置"],
      "required_external_facts": ["资质或荣誉证明", "医院授权", "有效期"],
      "indeterminate_boundary": "内容出现资质或荣誉称号不自动证明虚构。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则6.3", "legacy.rule-019.other.honor_fake"]
    }
  ],
  "migration_notes": {
    "from_worker_baseline": "Worker 当前的 communication.short_recording/20260906.1 只有 direct、absolute、fear.exaggeration 三条规则，属于最小可执行占位基线，不是本最终完整版。",
    "from_historical_sql": "历史 SQL 的 20260904.1 结构化规则卡提供了执行字段和边界，但把历史规则2.2与6.1合并；本文件为保留完整业务语义，将其拆回两个规则身份，并明确它们的关联。",
    "canonical_rule_source": "以后规则讨论、提示词设计、数据库迁移和测试用例均以本文件为基础；历史 Markdown、历史 SQL 和 Worker catalog 只作为归档，不再作为规则定义来源。",
    "implementation_warning": "本文件是规则规范和迁移基准，不代表所有规则已经进入当前运行 API。规则进入数据库和运行规则集前，必须依据 status、required_external_facts 和 validation_status 执行对应的发布审核。"
  }
}
$canonical$::jsonb AS document
),
catalog AS (
  SELECT id FROM guard_rule_catalog_versions WHERE version = (SELECT document->>'version' FROM canonical)
)
INSERT INTO guard_rule_set_versions (
  catalog_id, tenant_id, rule_set_code, rule_set_name, subject, source_kind, version, status, role_codes, source_types, applicability, notes, definition, published_at
)
SELECT catalog.id, NULL, rule_set->>'code', rule_set->>'name', rule_set->>'subject', 'platform', canonical.document->>'version', rule_set->>'status', COALESCE(rule_set->'role_codes', '[]'::jsonb), COALESCE(rule_set->'source_types', '[]'::jsonb), jsonb_build_object('role_codes', COALESCE(rule_set->'role_codes', '[]'::jsonb), 'source_types', COALESCE(rule_set->'source_types', '[]'::jsonb)), COALESCE(rule_set->>'notes', ''), rule_set, CASE WHEN rule_set->>'status' = 'published' THEN NOW() ELSE NULL END
FROM canonical
CROSS JOIN catalog
CROSS JOIN LATERAL jsonb_array_elements(canonical.document->'rule_sets') AS rule_set
ON CONFLICT DO NOTHING;

WITH canonical AS (
  SELECT 
$canonical$
{
  "schema_version": "1.0",
  "status": "canonical_current_baseline",
  "title": "合规卫士沟通与内容合规规则集",
  "version": "20260911.1",
  "purpose": "本文件是合规卫士当前规则讨论和后续实现的唯一基础。它自包含保存规则定义、业务说明、适用范围、判断边界和规则集成员关系，后续不需要回看历史规则文档或历史迁移 SQL。",
  "execution_policy": {
    "system_role": "合规引擎只发现需要医院查看的具体问题，不自动确认违规、不定责、不处罚。",
    "finding_granularity": "一次输入资料与一条规则最多形成一条发现；同一输入同一规则的多处证据合并到一条发现；同一输入不同规则分别形成发现；不同输入不得合并。",
    "llm_policy": "规则为大模型提供检查范围、判断标准、例外和证据要求；最终结论由医院复核。",
    "status_policy": "published 表示已进入对应规则集；draft 表示定义已保留但当前不应仅凭现有输入自动产生正式待核查发现。",
    "source_policy": "平台规则和医院本地规则分开管理；本院规则可以补充或收严平台规则，不能静默放宽平台底线。"
  },
  "field_definitions": {
    "rule_code": "规则的稳定编码。",
    "legacy_rule_number": "历史业务规则编号，仅用于追溯，不改变当前规则身份。",
    "subject": "规则处理的资料类型：communication 或 content。",
    "applicable_rule_sets": "规则进入哪些场景规则集。",
    "status": "当前发布状态。published 进入规则集，draft 只保留定义和待补资料要求。",
    "judgment_standard": "大模型和复核人员判断时必须回答的业务问题。",
    "trigger_conditions": "值得检查的表述或事实组合，不等于自动确认违规。",
    "exclusion_conditions": "出现这些条件时，不应仅凭本规则形成肯定性发现，或应降低为需要补充资料的候选。",
    "required_evidence": "发现和人工复核应尽量提供的证据。",
    "required_external_facts": "录音或内容本身之外必须补充的事实。",
    "indeterminate_boundary": "仅凭当前输入无法确定的边界。",
    "validation_status": "当前规则的验证状态。"
  },
  "rule_sets": [
    {
      "code": "communication.doctor.outpatient",
      "name": "医生门诊沟通规则集",
      "subject": "communication",
      "role_codes": ["doctor", "doctor_assistant"],
      "source_types": ["recording"],
      "status": "published",
      "included_rule_codes": [
        "communication.guarantee.direct",
        "communication.guarantee.absolute",
        "communication.guarantee.case",
        "communication.guarantee.duration",
        "communication.misleading.data_unverified",
        "communication.fear.exaggeration",
        "communication.fear.panic",
        "communication.fear.compare",
        "communication.scope.cross_department",
        "communication.scope.untrained_technology"
      ],
      "notes": "涉及价格成交、内容发布和必须核验外部事实的规则暂不作为仅凭医生录音自动检查的正式规则。"
    },
    {
      "code": "communication.consultant.consultation",
      "name": "咨询师咨询成交沟通规则集",
      "subject": "communication",
      "role_codes": ["consultant"],
      "source_types": ["recording"],
      "status": "published",
      "included_rule_codes": [
        "communication.guarantee.direct",
        "communication.guarantee.absolute",
        "communication.guarantee.case",
        "communication.guarantee.duration",
        "communication.misleading.exclusivity",
        "communication.misleading.disparage",
        "communication.misleading.urgency",
        "communication.misleading.data_unverified",
        "communication.fear.exaggeration",
        "communication.fear.panic",
        "communication.fear.compare",
        "communication.price.on_site_increase"
      ],
      "notes": "需要价格、活动或预约事实的规则保留为候选规则；没有外部事实时不得自动认定。"
    },
    {
      "code": "content.pre_publish",
      "name": "宣传内容发布前检查规则集",
      "subject": "content",
      "role_codes": [],
      "source_types": ["content_item", "script", "copy", "image_text"],
      "status": "draft",
      "included_rule_codes": [
        "content.price.false_original",
        "content.price.hidden_fee",
        "content.data.unverified",
        "content.privacy.patient",
        "content.honor.unverified"
      ],
      "notes": "内容中心正式接入和价格、授权、资质资料接入后发布。"
    }
  ],
  "rules": [
    {
      "rule_code": "communication.guarantee.direct",
      "legacy_rule_number": "1.1",
      "name": "直接保证诊疗结果",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条：不得对诊疗效果作出保证性承诺。"],
      "judgment_standard": "判断工作人员是否明确把确定的治疗结果、疗效或恢复结果承诺给当前患者，而不是仅说明可能性、条件或一般经验。",
      "trigger_conditions": ["保证性表达与治愈、治好、康复、恢复、痊愈或类似结果同时指向当前患者。"],
      "exclusion_conditions": ["不能保证", "无法保证", "不保证", "不敢保证", "不能承诺", "明确说明个体差异或结果不确定。"],
      "violation_examples": ["我保证你一定能治好。", "保证你术后视力能恢复到1.5。", "我们保证种植后20年不会掉。"],
      "compliant_examples": ["成功率在95%以上，但因个体差异，不能保证。", "大多数患者术后视力可以恢复到1.2-1.5。", "如果按医嘱护理，用20年问题不大，但不能保证。"],
      "fact_definition": "同一上下文中出现保证性表达和诊疗结果表达，并将结果指向当前患者。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "必要的前后文"],
      "required_external_facts": [],
      "indeterminate_boundary": "片段不足以判断说话人是在转述患者观点、引用问题还是本人承诺时，只形成候选发现。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "technical_validation",
      "source_basis": ["历史规则1.1", "legacy.rule-001.guarantee.direct"]
    },
    {
      "rule_code": "communication.guarantee.absolute",
      "legacy_rule_number": "1.2",
      "name": "绝对化诊疗效果表述",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条。"],
      "judgment_standard": "判断工作人员是否用一定、肯定、绝对、必然等绝对化语言描述诊疗效果、成功率、安全性或恢复结果；必须结合上下文，不能因为单个词出现就形成发现。",
      "trigger_conditions": ["绝对化或必然性表达与能、会等结果表达及治愈、治好、康复、恢复、痊愈等结果词形成同一语义。"],
      "exclusion_conditions": ["不能保证一定", "不一定能", "不一定会", "无法保证一定", "未必能", "不敢肯定", "患者提问而工作人员明确否定或限定。"],
      "violation_examples": ["你这个一定能治好。", "肯定会恢复的。", "绝对能看到1.5。"],
      "compliant_examples": ["有很大概率能治好，但不能说一定。", "大多数情况下会恢复，但也有个体差异。", "我们会尽力帮你恢复视力。"],
      "fact_definition": "同一上下文同时出现绝对化表达、结果可能性表达和诊疗结果表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "前后文"],
      "required_external_facts": [],
      "indeterminate_boundary": "绝对化词可能出现在否定、引用、患者提问或医生纠正中，不能据此自动定性。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "technical_validation",
      "source_basis": ["历史规则1.2", "legacy.rule-002.guarantee.implied"]
    },
    {
      "rule_code": "communication.guarantee.case",
      "legacy_rule_number": "1.3",
      "name": "以案例暗示当前患者结果",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条；反不正当竞争法关于引人误解宣传的相关规定。"],
      "judgment_standard": "判断工作人员是否把其他患者的成功案例、数量或结果直接推导为当前患者也会获得相同结果。",
      "trigger_conditions": ["成功案例或既往结果与“你也会、你也能、你也一样、没一个失败、全部成功、百分之百成功”等当前患者结果暗示同时出现。"],
      "exclusion_conditions": ["每个人情况不同", "因人而异", "不能保证", "不代表", "不一定", "仅客观介绍案例且没有推导当前患者结果。"],
      "violation_examples": ["上个月张女士做完现在1.5，你也会一样的。", "我们做过800例，没一个失败的，你放心。"],
      "compliant_examples": ["上个月张女士术后恢复得不错，但每个人情况不同。", "我们做过800例，成功率很高，但不能说100%成功。"],
      "fact_definition": "片段同时包含成功案例或既往结果引用，以及对当前患者结果的一致性暗示或绝对成功表述。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "可取得时的上下文"],
      "required_external_facts": [],
      "indeterminate_boundary": "引用案例本身不等于违规；无法判断案例真实性、患者是否主动询问或是否说明个体差异时，只作候选。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则1.3", "legacy.rule-003.guarantee.case"]
    },
    {
      "rule_code": "communication.guarantee.duration",
      "legacy_rule_number": "1.4",
      "name": "无条件承诺疗效维持时间",
      "category": "保证疗效",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《医疗广告管理办法》第七条。"],
      "judgment_standard": "判断工作人员是否把疗效、器械效果或服务结果无条件承诺为长期、终身、永久或固定年限。",
      "trigger_conditions": ["一辈子、终身、永久、20年、几十年等时间表达与能用、有效、不会掉、不用换、一直用、维持等无条件结果表达同时出现。"],
      "exclusion_conditions": ["护理得当", "理论上", "可能", "因人而异", "需要复查", "不保证", "仅说明理论寿命而未承诺患者结果。"],
      "violation_examples": ["种植牙能用一辈子。", "保证20年不会掉。", "做完ICL终身有效。"],
      "compliant_examples": ["如果护理得当，种植牙可以用很多年，有患者用了20年以上。", "ICL晶体理论上可以长期使用，但也可能因某些原因需要取出。"],
      "fact_definition": "同一片段同时出现长期时长表达和无条件效果、使用或维持结果表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": [],
      "indeterminate_boundary": "客观经验、条件性说明或器械理论寿命不当然构成承诺，必须结合上下文复核。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则1.4", "legacy.rule-004.guarantee.duration"]
    },
    {
      "rule_code": "communication.misleading.exclusivity",
      "legacy_rule_number": "2.1",
      "name": "绝对化疗效、设备或方案排他宣传",
      "category": "诱导消费",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条；《医疗广告管理办法》关于保证性和引人误解宣传的规定。"],
      "judgment_standard": "判断咨询师是否把具体诊疗方案、技术、设备或机构表述为唯一、最好、最佳、独家或全国唯一。",
      "trigger_conditions": ["最好、最佳、唯一、独家、全国唯一等排他表达与方案、治疗、方法、技术、设备、医院或机构对象同时出现。"],
      "exclusion_conditions": ["之一", "各有优势", "未必", "不一定", "仅陈述客观配置或明确限定比较范围。"],
      "violation_examples": ["这是最好的治疗方案。", "唯一能治愈的方法。", "我们是全国唯一引进这个设备的。"],
      "compliant_examples": ["这是目前常用的治疗方案之一。", "这个方法效果不错，但也有其他选择。", "我们引进了这个设备，在本地区较为先进。"],
      "fact_definition": "同一片段同时出现绝对化、排他性表达和被推广的方案、技术、设备或机构对象。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "可取得时的宣传或设备事实"],
      "required_external_facts": [],
      "indeterminate_boundary": "医生基于病情进行医学比较不直接适用本规则；咨询师候选也不自动确认虚假宣传。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则2.1", "legacy.rule-005.misleading.exaggerate"]
    },
    {
      "rule_code": "communication.misleading.disparage",
      "legacy_rule_number": "2.2",
      "name": "无依据贬低其他方案或机构",
      "category": "诱导消费",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条。"],
      "judgment_standard": "判断咨询师是否把其他医院、医生、方案或传统方法与不行、骗人、太差、没用、落后等贬损表达组合，且没有给出可核验依据。",
      "trigger_conditions": ["其他医院、其他方案、传统方法、其他医生等对象与明确贬损表达同时出现。"],
      "exclusion_conditions": ["各有优势", "不代表", "不能一概而论", "要看情况", "存在可核验的比较依据并明确限定适用条件。"],
      "violation_examples": ["别的医院都不行，只有我们能做。", "传统方法效果差，都是骗人的。", "那家医院的设备太老了。"],
      "compliant_examples": ["我们在这方面有丰富经验，但其他医院也有各自的优势。", "传统方法也有效果，只是我们这个方法更先进一些。", "不同医院的设备配置不同，各有特点。"],
      "fact_definition": "片段同时出现可识别的其他机构、医生或方案对象，以及无依据的贬损表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间", "可取得时的比较依据"],
      "required_external_facts": ["比较对象的设备、技术或服务事实，视具体表达而定"],
      "indeterminate_boundary": "医生可能基于病情作医学比较；咨询师候选也需人工判断是否有事实依据。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则2.2", "历史规则6.1", "legacy.rule-006.misleading.degrade", "legacy.rule-017.other.degrade"]
    },
    {
      "rule_code": "communication.misleading.urgency",
      "legacy_rule_number": "2.3",
      "name": "非医学依据的成交紧迫施压",
      "category": "诱导消费",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条；价格和促销信息真实性相关要求。"],
      "judgment_standard": "判断时间、名额、涨价、活动或排队表达是否以不真实或不完整的外部事实推动患者立即成交。",
      "trigger_conditions": ["今天、现在、马上、只剩名额、明天涨价、下月排队等紧迫表达与优惠、活动、名额或预约同时出现。"],
      "exclusion_conditions": ["真实活动且信息完整", "真实预约紧张且可核验", "只是建议尽早预约而没有虚构后果。"],
      "violation_examples": ["今天不做，明天就涨价了。", "现在只剩3个名额了。", "这个月不做，下个月就要排队半年。"],
      "compliant_examples": ["我们目前有优惠活动，具体可以咨询前台。", "近期预约的患者比较多，建议您尽早决定。", "医生的档期比较满，建议提前预约。"],
      "fact_definition": "录音中的时间、名额、涨价或排队表达与实际活动、价格或预约事实不一致。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["活动规则", "名额或预约记录", "价格或有效期"],
      "indeterminate_boundary": "录音单独不能证明紧迫表达不真实或不当。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则2.3", "legacy.rule-007.misleading.urgency"]
    },
    {
      "rule_code": "communication.misleading.data_unverified",
      "legacy_rule_number": "2.4",
      "name": "无法核验的宣传数据",
      "category": "诱导消费",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条。"],
      "judgment_standard": "判断工作人员是否使用满意度、成功率、无事故、万例等数据，并将其作为可信结果或成交依据，但医院无法提供来源、统计口径或有效期。",
      "trigger_conditions": ["98%满意度、万例无事故、百分之百成功等具体数据与宣传或成交语境同时出现。"],
      "exclusion_conditions": ["有可核验来源、统计口径和有效期", "仅表达主观感受且没有伪装成统计数据。"],
      "violation_examples": ["我们的患者满意度98%。", "万例手术无一例事故。"],
      "compliant_examples": ["大多数患者对手术效果比较满意。", "我们非常重视手术安全，有完善的质控流程。"],
      "fact_definition": "沟通中使用统计或效果数据，但缺少可核验来源、口径或有效期。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["数据来源", "统计口径", "有效期", "必要时的审计或质控记录"],
      "indeterminate_boundary": "出现数字本身不等于虚假数据；没有外部资料时只能提示待核验。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则2.4", "legacy.rule-008.misleading.data"]
    },
    {
      "rule_code": "communication.fear.exaggeration",
      "legacy_rule_number": "3.1",
      "name": "夸大风险推动决策",
      "category": "制造焦虑",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["医疗风险告知和医疗宣传真实性相关要求。"],
      "judgment_standard": "判断工作人员是否通过夸大疾病严重程度、拖延后果或时间压力推动当前患者立即作出诊疗决定，而不是基于事实进行合理风险告知。",
      "trigger_conditions": ["很严重、非常危险、再不做就来不及了、拖不得等严重或紧迫表达指向当前患者决定。"],
      "exclusion_conditions": ["不用担心", "不必过度担心", "没有那么严重", "不严重", "有医学检查、病情和处理时限依据。"],
      "violation_examples": ["你这个很严重，再不做就瞎了。", "这个必须马上手术，否则会恶化。", "你这个拖不得，再拖就完了。"],
      "compliant_examples": ["您的白内障已到中期，建议尽快手术，以免影响日常生活。", "这个病情需要及时治疗，但也不用过度紧张。", "建议您尽早手术，但具体时间可以和医生商量。"],
      "fact_definition": "原始转写片段出现可能利用严重后果或时间压力推动决策的表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["涉及医学严重程度或时限时，应补充病历、检查或医学依据"],
      "indeterminate_boundary": "严重程度和处理时限需要结合患者病情、检查结果和医学依据；本规则只能提供候选线索。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "technical_validation",
      "source_basis": ["历史规则3.1", "legacy.rule-009.fear.severity"]
    },
    {
      "rule_code": "communication.fear.panic",
      "legacy_rule_number": "3.2",
      "name": "不做即发生绝对严重后果",
      "category": "制造焦虑",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["医疗风险告知和医疗宣传真实性相关要求。"],
      "judgment_standard": "判断工作人员是否把不做某项治疗直接关联失明、全掉光或其他绝对严重后果，并以此推动患者决定。",
      "trigger_conditions": ["不做、不治疗、不手术、不种牙、不矫正等表达与失明、全掉光、瞎了、恶化或严重后果直接关联。"],
      "exclusion_conditions": ["有可能", "定期检查", "因人而异", "医生评估", "需要检查", "明确表达风险概率和条件。"],
      "violation_examples": ["不种牙的话，其他牙齿也会松动，最后全掉光。", "近视不矫正，度数会越来越深，最后会失明。"],
      "compliant_examples": ["缺牙后，邻牙可能会移位，建议考虑种植修复。", "近视度数可能会加深，建议定期检查。"],
      "fact_definition": "同一片段把不做治疗或矫正与绝对严重后果直接关联。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["医生场景下的病历或检查事实", "必要时的医学依据"],
      "indeterminate_boundary": "医学风险说明可能合理，尤其医生场景必须结合病历和检查事实复核，系统不确认夸大病情。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则3.2", "legacy.rule-010.fear.panic"]
    },
    {
      "rule_code": "communication.fear.compare",
      "legacy_rule_number": "3.3",
      "name": "做与不做的夸张后果对比",
      "category": "制造焦虑",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.doctor.outpatient", "communication.consultant.consultation"],
      "legal_basis": ["医疗风险告知和医疗宣传真实性相关要求。"],
      "judgment_standard": "判断工作人员是否把治疗后的绝对正面结果与不治疗后的绝对负面结果并列，以夸张对比推动当前患者选择。",
      "trigger_conditions": ["治疗后、做完等正向结果与不做、不治疗等负向结果同时出现，且两边都使用绝对化或极端结果。"],
      "exclusion_conditions": ["可以选择", "也可以", "个人选择", "因人而异", "客观说明不同方案的风险和收益。"],
      "violation_examples": ["做了你就能看得清清楚楚；不做你就要戴一辈子眼镜，还会越来越深。"],
      "compliant_examples": ["手术后视力会有改善，但也可以选择继续戴眼镜，这是您的个人选择。"],
      "fact_definition": "同一片段同时对治疗后和不治疗后的结果作绝对化正负对比。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["医生场景下的病历或检查事实", "涉及治疗效果时的医学依据"],
      "indeterminate_boundary": "治疗方案比较可能是必要告知，医生场景尤其需要医学事实复核。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则3.3", "legacy.rule-011.fear.compare"]
    },
    {
      "rule_code": "content.price.false_original",
      "legacy_rule_number": "4.1",
      "name": "虚构原价或虚假优惠",
      "category": "价格欺诈",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["《价格法》第十四条：不得虚构原价、虚假优惠折价。"],
      "judgment_standard": "判断内容宣称的原价、市场价或优惠是否与可核验的价格表、活动规则和生效记录不一致。",
      "trigger_conditions": ["内容先报高价再宣布大幅优惠，或使用市场价、原价、活动价作为购买依据。"],
      "exclusion_conditions": ["价格和活动有有效记录", "活动期限、适用条件和比较价格完整披露。"],
      "violation_examples": ["原价3万，现在活动价1.5万，但实际从未卖过3万。", "市场价5万，我们只要2万，但没有市场价依据。"],
      "compliant_examples": ["我们的价格是2万，目前有优惠活动。", "不同医院价格不同，我们的价格在XX元左右。"],
      "fact_definition": "内容宣称的原价、市场价或优惠与可核验价格和活动资料不一致。",
      "required_evidence": ["内容版本快照", "发布渠道和时间"],
      "required_external_facts": ["价格表", "活动规则", "价格生效记录"],
      "indeterminate_boundary": "文字中的原价和优惠不能单独证明价格虚假。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则4.1", "legacy.rule-012.price.fake_original"]
    },
    {
      "rule_code": "content.price.hidden_fee",
      "legacy_rule_number": "4.2",
      "name": "隐瞒费用构成",
      "category": "价格欺诈",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["《价格法》及价格信息明示相关要求。"],
      "judgment_standard": "判断内容报价是否遗漏应披露且会影响总价的费用、材料、检查、复查或适用条件。",
      "trigger_conditions": ["只展示单项低价，而项目实际还包含牙冠、骨粉、检查、复查或其他必要费用。"],
      "exclusion_conditions": ["已明确项目范围和费用构成", "已说明其他费用另算及预计总额或区间。"],
      "violation_examples": ["种植牙1万一颗，但不说还要加牙冠、骨粉等费用。", "ICL手术2万，但不说术前检查和术后复查费用。"],
      "compliant_examples": ["种植体费用1万，加上牙冠和其他费用，总计约1.5到2万。", "手术费用2万，术前检查和术后复查另算，总共约2.5万。"],
      "fact_definition": "内容中的项目报价遗漏会影响总价的费用构成或适用条件。",
      "required_evidence": ["内容版本快照", "价格文案所在位置"],
      "required_external_facts": ["项目费用构成", "价格表", "适用条件"],
      "indeterminate_boundary": "单一价格文案不能自动证明隐瞒费用。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则4.2", "legacy.rule-013.price.hidden_fee"]
    },
    {
      "rule_code": "communication.price.on_site_increase",
      "legacy_rule_number": "4.3",
      "name": "电话低价与到店报价不一致",
      "category": "价格欺诈",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《价格法》第十四条。"],
      "judgment_standard": "判断首次沟通报价与到店后的相同项目报价是否不一致，且不存在已告知的材料、项目或服务范围差异。",
      "trigger_conditions": ["电话或首次沟通报低价，到店后以材料、效果或其他理由引导到更高价格。"],
      "exclusion_conditions": ["项目或材料不同且已告知", "价格区间已完整说明", "到店报价变化有真实项目依据。"],
      "violation_examples": ["电话说种植牙5000一颗，到店后说5000是最便宜材料，建议用2万的。"],
      "compliant_examples": ["种植牙根据材料不同，价格从5000到2万不等，建议来院详细了解。"],
      "fact_definition": "首次沟通报价与到院后的相同项目报价不一致，且不存在可核验的材料、项目或服务范围差异。",
      "required_evidence": ["首次报价录音或记录", "到院报价记录", "相关对话时间"],
      "required_external_facts": ["首次报价", "到院报价", "项目价格表", "到院记录"],
      "indeterminate_boundary": "单段录音不能证明实际成交价格或费用构成。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则4.3", "legacy.rule-014.price.on_site"]
    },
    {
      "rule_code": "communication.scope.cross_department",
      "legacy_rule_number": "5.1",
      "name": "表达服务范围与执业资质不一致",
      "category": "超范围执业",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.doctor.outpatient"],
      "legal_basis": ["《执业医师法》第十四条。"],
      "judgment_standard": "判断人员在沟通中表达的服务能力是否与其可核验的执业范围、科室、排班或授权不一致。",
      "trigger_conditions": ["人员主动表示可以提供不属于其执业范围或科室范围的医疗服务。"],
      "exclusion_conditions": ["已转诊", "明确说明不在本人范围", "有有效授权和排班依据。"],
      "violation_examples": ["口腔科医生说我也会做双眼皮，来找我吧。", "眼科医生说我也能看牙，顺便给你看看。"],
      "compliant_examples": ["这个不在我的执业范围，我帮您联系眼科医生。", "这个需要口腔科医生来看，我给您转诊。"],
      "fact_definition": "人员表达的服务能力与其可核验的执业范围、科室或授权不一致。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["执业范围", "人员排班或科室", "实际服务项目", "授权记录"],
      "indeterminate_boundary": "录音不能自行证明超范围执业。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则5.1", "legacy.rule-015.scope.cross_department"]
    },
    {
      "rule_code": "communication.scope.untrained_technology",
      "legacy_rule_number": "5.2",
      "name": "表达使用新技术与培训授权不一致",
      "category": "超范围执业",
      "subject": "communication",
      "status": "draft",
      "applicable_rule_sets": ["communication.doctor.outpatient"],
      "legal_basis": ["《执业医师法》及医疗技术准入、授权相关要求。"],
      "judgment_standard": "判断人员是否表达可以使用新技术或设备，但培训、授权或资格资料不能支持该表达。",
      "trigger_conditions": ["工作人员表示自己可以操作新技术、新设备或新项目。"],
      "exclusion_conditions": ["有效培训和授权齐备", "由具备资格人员实际服务", "明确表示由专门医生负责。"],
      "violation_examples": ["这个新技术我也能做，但实际没有培训或授权。"],
      "compliant_examples": ["这个新技术我们医院有，由专门的医生负责。"],
      "fact_definition": "人员表达可使用新技术或设备，但培训、授权或资格资料不能支持该表达。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["培训记录", "设备或技术授权", "人员资格"],
      "indeterminate_boundary": "录音不能自行证明未经培训或无授权。",
      "output_type": "cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_missing_source",
      "source_basis": ["历史规则5.2", "legacy.rule-016.scope.untrained_tech"]
    },
    {
      "rule_code": "communication.other.peer_disparagement",
      "legacy_rule_number": "6.1",
      "name": "诋毁同行",
      "category": "其他",
      "subject": "communication",
      "status": "published",
      "applicable_rule_sets": ["communication.consultant.consultation"],
      "legal_basis": ["《反不正当竞争法》第八条。"],
      "judgment_standard": "判断工作人员是否对其他医院、医生或同行作出无依据的贬损表达，并以此突出自身服务。",
      "trigger_conditions": ["明确指向其他医院或医生的贬低、否定、侮辱性表达。"],
      "exclusion_conditions": ["各有特点", "客观比较且有依据", "不代表", "不能一概而论"],
      "violation_examples": ["别的医院都不行，只有我们能做。", "XX医院的医生水平太差了。"],
      "compliant_examples": ["我们在这方面有丰富经验。", "不同医院各有特点。"],
      "fact_definition": "指向同行对象的贬损表达，且无法提供客观比较依据。",
      "required_evidence": ["原始转写片段", "说话人", "起止时间"],
      "required_external_facts": ["比较依据，视具体表达而定"],
      "indeterminate_boundary": "该规则与“无依据贬低其他方案或机构”存在业务关联，但本最终版本保留原始规则身份；实现时可在展示层关联，不得重复制造两条发现。",
      "output_type": "machine_finding",
      "review_priority": "review",
      "validation_status": "test_material_required",
      "source_basis": ["历史规则6.1", "legacy.rule-017.other.degrade"]
    },
    {
      "rule_code": "content.privacy.patient",
      "legacy_rule_number": "6.2",
      "name": "患者隐私或案例展示未获授权",
      "category": "其他",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["患者隐私、个人信息保护和医疗案例授权相关要求。"],
      "judgment_standard": "判断内容是否展示可识别患者身份、照片、影像或案例信息，但无法提供匹配的授权和脱敏依据。",
      "trigger_conditions": ["姓名、年龄、单位、照片、影像或其他可识别信息与患者案例展示同时出现。"],
      "exclusion_conditions": ["患者已授权", "已按传播范围完成脱敏", "内容使用完全虚构或不可识别案例。"],
      "violation_examples": ["李女士，35岁，XX公司职员，上周在我们这里做了手术。", "展示未打码的患者照片。"],
      "compliant_examples": ["有位患者上周在我们这里做了相关治疗。", "展示患者照片并完成面部打码。"],
      "fact_definition": "内容展示可识别的患者身份、影像或案例信息，但无法提供匹配的授权和脱敏依据。",
      "required_evidence": ["内容版本快照", "图片或视频帧", "发布渠道"],
      "required_external_facts": ["患者授权", "脱敏范围", "传播渠道"],
      "indeterminate_boundary": "内容出现案例或照片不自动证明未经授权。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则6.2", "legacy.rule-018.other.privacy"]
    },
    {
      "rule_code": "content.honor.unverified",
      "legacy_rule_number": "6.3",
      "name": "无法核验的医院或人员荣誉资质宣传",
      "category": "其他",
      "subject": "content",
      "status": "draft",
      "applicable_rule_sets": ["content.pre_publish"],
      "legal_basis": ["医疗机构和医务人员资质、荣誉宣传真实性相关要求。"],
      "judgment_standard": "判断内容宣称的医院等级、人员资质或荣誉称号是否有有效证明材料、医院授权和有效期支持。",
      "trigger_conditions": ["三甲医院、医学会会员、权威专家、荣誉称号或类似资质宣传无法关联有效证明。"],
      "exclusion_conditions": ["有权威证明", "医院授权有效", "资质或荣誉处于有效期内。"],
      "violation_examples": ["我们是三甲医院，但实际不是。", "我们医生是中华医学会会员，但实际不是。"],
      "compliant_examples": ["如实告知医院等级和医生资质。"],
      "fact_definition": "内容宣称的医院等级、人员资质或荣誉无法由有效证明材料支持。",
      "required_evidence": ["内容版本快照", "宣传文字或图片位置"],
      "required_external_facts": ["资质或荣誉证明", "医院授权", "有效期"],
      "indeterminate_boundary": "内容出现资质或荣誉称号不自动证明虚构。",
      "output_type": "content_cross_source_candidate",
      "review_priority": "review",
      "validation_status": "blocked_by_content_source",
      "source_basis": ["历史规则6.3", "legacy.rule-019.other.honor_fake"]
    }
  ],
  "migration_notes": {
    "from_worker_baseline": "Worker 当前的 communication.short_recording/20260906.1 只有 direct、absolute、fear.exaggeration 三条规则，属于最小可执行占位基线，不是本最终完整版。",
    "from_historical_sql": "历史 SQL 的 20260904.1 结构化规则卡提供了执行字段和边界，但把历史规则2.2与6.1合并；本文件为保留完整业务语义，将其拆回两个规则身份，并明确它们的关联。",
    "canonical_rule_source": "以后规则讨论、提示词设计、数据库迁移和测试用例均以本文件为基础；历史 Markdown、历史 SQL 和 Worker catalog 只作为归档，不再作为规则定义来源。",
    "implementation_warning": "本文件是规则规范和迁移基准，不代表所有规则已经进入当前运行 API。规则进入数据库和运行规则集前，必须依据 status、required_external_facts 和 validation_status 执行对应的发布审核。"
  }
}
$canonical$::jsonb AS document
)
INSERT INTO guard_rule_set_rule_versions (rule_set_version_id, rule_version_id, position)
SELECT rule_set_row.id, rule_row.id, members.position
FROM canonical
CROSS JOIN LATERAL jsonb_array_elements(canonical.document->'rule_sets') AS rule_set
CROSS JOIN LATERAL jsonb_array_elements_text(rule_set->'included_rule_codes') WITH ORDINALITY AS members(rule_code, position)
JOIN guard_rule_set_versions rule_set_row ON rule_set_row.tenant_id IS NULL AND rule_set_row.rule_set_code = rule_set->>'code' AND rule_set_row.version = canonical.document->>'version'
JOIN guard_rule_versions rule_row ON rule_row.tenant_id IS NULL AND rule_row.rule_code = members.rule_code AND rule_row.version = canonical.document->>'version'
ON CONFLICT DO NOTHING;

COMMIT;
