package compliance

type builtinRuleSeed struct {
	ID              string
	Code            string
	Name            string
	Category        string
	Scope           string
	Severity        string
	TriggerType     string
	Conditions      JSONMap
	Description     string
	LegalBasis      string
	SuggestedScript string
	Examples        RuleExamples
}

func builtinRuleSeeds() []builtinRuleSeed {
	return []builtinRuleSeed{
		{
			ID:              "rule-001",
			Code:            "guarantee.direct",
			Name:            "规则1.1：直接保证",
			Category:        "guarantee",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"保证", "治愈", "治好", "康复", "恢复", "痊愈"}, "operator": "AND"},
			Description:     "直接对诊疗效果作出保证性承诺，属于第一优先级风险。",
			LegalBasis:      "《医疗广告管理办法》第七条：不得对诊疗效果作出保证性承诺。",
			SuggestedScript: "成功率较高，但因个体差异，不能保证一定达到某个结果。",
			Examples: RuleExamples{
				Risky: []string{"我保证你一定能治好", "保证你术后视力能恢复到1.5", "我们保证种植后20年不会掉"},
				Safe:  []string{"成功率在95%以上，但因个体差异，不能保证", "大多数患者术后视力可以恢复到1.2-1.5", "如果按医嘱护理，用20年问题不大，但不能保证"},
			},
		},
		{
			ID:              "rule-002",
			Code:            "guarantee.implied",
			Name:            "规则1.2：暗示保证",
			Category:        "guarantee",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "一定|肯定|绝对|必然 + 能|会 + 治好|康复|恢复"},
			Description:     "使用绝对化表达，构成变相保证。",
			LegalBasis:      "《医疗广告管理办法》第七条：不得含有保证性承诺内容。",
			SuggestedScript: "有较大概率恢复，但仍需根据检查结果和个体差异判断。",
			Examples: RuleExamples{
				Risky: []string{"你这个一定能治好", "肯定会恢复的", "绝对能看到1.5"},
				Safe:  []string{"有很大概率能治好，但不能说一定", "大多数情况下会恢复，但也有个体差异", "我们会尽力帮你恢复视力"},
			},
		},
		{
			ID:              "rule-003",
			Code:            "guarantee.case",
			Name:            "规则1.3：案例保证",
			Category:        "guarantee",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "成功案例 + 你也会一样/一样的/肯定"},
			Description:     "讲述其他患者的成功案例并暗示个体结果一致，构成变相保证。",
			LegalBasis:      "医疗广告与诊疗沟通规范，不得通过个案暗示普遍效果。",
			SuggestedScript: "上个月张女士术后恢复得不错，但每个人情况不同。",
			Examples: RuleExamples{
				Risky: []string{"上个月张女士做完，现在1.5，你也会一样的", "我们做过800例，没一个失败的，你放心"},
				Safe:  []string{"上个月张女士术后恢复得不错，但每个人情况不同", "我们做过800例，成功率很高，但不能说100%成功"},
			},
		},
		{
			ID:              "rule-004",
			Code:            "guarantee.duration",
			Name:            "规则1.4：承诺维持时间",
			Category:        "guarantee",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"一辈子", "20年", "终身", "永久"}, "operator": "OR"},
			Description:     "承诺具体维持时间或永久有效，属于风险承诺。",
			LegalBasis:      "医疗广告与诊疗沟通规范，不得对长期效果作绝对承诺。",
			SuggestedScript: "如果护理得当，种植牙可以用很多年，有患者用了20年以上。",
			Examples: RuleExamples{
				Risky: []string{"种植牙能用一辈子", "保证20年不会掉", "做完ICL终身有效"},
				Safe:  []string{"如果护理得当，种植牙可以用很多年，有患者用了20年以上", "ICL晶体理论上可以长期使用，但也可能因某些原因需要取出"},
			},
		},
		{
			ID:              "rule-005",
			Code:            "misleading.exaggerate",
			Name:            "规则2.1：夸大疗效",
			Category:        "misleading",
			Scope:           "communication",
			Severity:        "medium",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"最好", "最佳", "唯一", "独家"}, "operator": "OR"},
			Description:     "使用绝对化或夸张性描述推广方案，容易误导患者。",
			LegalBasis:      "《医疗广告管理办法》与《反不正当竞争法》关于虚假或引人误解宣传的要求。",
			SuggestedScript: "这是目前常用的治疗方案之一。",
			Examples: RuleExamples{
				Risky: []string{"这是最好的治疗方案", "唯一能治愈的方法", "我们是全国唯一引进这个设备的"},
				Safe:  []string{"这是目前常用的治疗方案之一", "这个方法效果不错，但也有其他选择", "我们引进了这个设备，在本地区较为先进"},
			},
		},
		{
			ID:              "rule-006",
			Code:            "misleading.degrade",
			Name:            "规则2.2：贬低其他方案",
			Category:        "misleading",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "别的医院/方案/医生 + 不行/骗人/差"},
			Description:     "贬低其他医院、方案或医生，诱导患者排他性选择。",
			LegalBasis:      "《医疗广告管理办法》及诚信宣传要求。",
			SuggestedScript: "我们在这方面有丰富经验，但其他医院也有各自的优势。",
			Examples: RuleExamples{
				Risky: []string{"别的医院都不行，只有我们能做", "传统方法效果差，都是骗人的", "那家医院的设备太老了"},
				Safe:  []string{"我们在这方面有丰富经验，但其他医院也有各自的优势", "传统方法也有效果，只是我们这个方法更先进一些", "不同医院的设备配置不同，各有特点"},
			},
		},
		{
			ID:              "rule-007",
			Code:            "misleading.urgency",
			Name:            "规则2.3：制造紧迫感",
			Category:        "misleading",
			Scope:           "communication",
			Severity:        "medium",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"今天不做", "明天就涨价", "只剩", "下个月", "排队半年"}, "operator": "OR"},
			Description:     "通过优惠、名额或排队时长制造不必要的紧迫感。",
			LegalBasis:      "医疗服务宣传与消费者权益保护相关要求。",
			SuggestedScript: "我们目前有优惠活动，具体可以咨询前台。",
			Examples: RuleExamples{
				Risky: []string{"今天不做，明天就涨价了", "现在只剩3个名额了", "这个月不做，下个月就要排队半年"},
				Safe:  []string{"我们目前有优惠活动，具体可以咨询前台", "近期预约的患者比较多，建议您尽早决定", "医生的档期比较满，建议提前预约"},
			},
		},
		{
			ID:              "rule-008",
			Code:            "misleading.data",
			Name:            "规则2.4：虚假数据",
			Category:        "misleading",
			Scope:           "content",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "满意度/无事故/万例 + 无法验证"},
			Description:     "使用无法验证的数据或缺乏证据支撑的统计结论。",
			LegalBasis:      "《反不正当竞争法》第八条关于虚假或引人误解宣传的要求。",
			SuggestedScript: "大多数患者对手术效果比较满意。",
			Examples: RuleExamples{
				Risky: []string{"我们的患者满意度98%", "万例手术无一例事故"},
				Safe:  []string{"大多数患者对手术效果比较满意", "我们非常重视手术安全，有完善的质控流程"},
			},
		},
		{
			ID:              "rule-009",
			Code:            "fear.severity",
			Name:            "规则3.1：夸大病情",
			Category:        "fear_mongering",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"很严重", "非常危险", "再不做就来不及了", "拖不得"}, "operator": "OR"},
			Description:     "通过夸大风险推动患者快速决策。",
			LegalBasis:      "医疗服务宣传和消费者保护要求，禁止利用恐惧进行误导。",
			SuggestedScript: "病情需要及时处理，但具体风险和时间判断应基于检查结果说明。",
			Examples: RuleExamples{
				Risky: []string{"你这个很严重，再不做就瞎了", "这个必须马上手术，否则会恶化", "你这个拖不得，再拖就完了"},
				Safe:  []string{"您的白内障已到中期，建议尽快手术，以免影响日常生活", "这个病情需要及时治疗，但也不用过度紧张", "建议您尽早手术，但具体时间可以和医生商量"},
			},
		},
		{
			ID:              "rule-010",
			Code:            "fear.panic",
			Name:            "规则3.2：制造恐慌",
			Category:        "fear_mongering",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "不做 + 最后全掉光/失明/严重后果"},
			Description:     "通过描述严重后果制造恐慌。",
			LegalBasis:      "医疗服务宣传和消费者保护要求，禁止利用恐惧进行误导。",
			SuggestedScript: "缺牙后，邻牙可能会移位，建议考虑种植修复。",
			Examples: RuleExamples{
				Risky: []string{"不种牙的话，其他牙齿也会松动，最后全掉光", "近视不矫正，度数会越来越深，最后会失明"},
				Safe:  []string{"缺牙后，邻牙可能会移位，建议考虑种植修复", "近视度数可能会加深，建议定期检查"},
			},
		},
		{
			ID:              "rule-011",
			Code:            "fear.compare",
			Name:            "规则3.3：对比渲染",
			Category:        "fear_mongering",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "做了你就能...；不做你就..."},
			Description:     "对比做与不做的后果，夸大不做的负面结果。",
			LegalBasis:      "医疗服务宣传和消费者保护要求，禁止利用对比渲染制造压力。",
			SuggestedScript: "手术后视力会有改善，但也可以选择继续戴眼镜，这是您的个人选择。",
			Examples: RuleExamples{
				Risky: []string{"做了，你就能看得清清楚楚；不做，你就要戴一辈子眼镜，还会越来越深"},
				Safe:  []string{"手术后视力会有改善，但也可以选择继续戴眼镜，这是您的个人选择"},
			},
		},
		{
			ID:              "rule-012",
			Code:            "price.fake_original",
			Name:            "规则4.1：虚假原价",
			Category:        "price_fraud",
			Scope:           "content",
			Severity:        "critical",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"原价", "现在优惠", "市场价"}, "operator": "OR"},
			Description:     "先报高价再说优惠，或者虚构市场价。",
			LegalBasis:      "《价格法》第十四条关于虚构原价、虚假优惠折价的要求。",
			SuggestedScript: "我们的价格是2万，目前有优惠活动。",
			Examples: RuleExamples{
				Risky: []string{"原价3万，现在活动价1.5万", "市场价5万，我们只要2万"},
				Safe:  []string{"我们的价格是2万，目前有优惠活动", "不同医院的价格不同，我们的价格在XX元左右"},
			},
		},
		{
			ID:              "rule-013",
			Code:            "price.hidden_fee",
			Name:            "规则4.2：隐瞒费用",
			Category:        "price_fraud",
			Scope:           "content",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "只说部分费用，隐瞒其他费用"},
			Description:     "只说局部费用，不披露总费用构成。",
			LegalBasis:      "《价格法》第十四条及消费告知规范。",
			SuggestedScript: "种植体费用1万，加上牙冠和其他费用，总计约1.5-2万。",
			Examples: RuleExamples{
				Risky: []string{"种植牙1万一颗", "ICL手术2万"},
				Safe:  []string{"种植体费用1万，加上牙冠和其他费用，总计约1.5-2万", "手术费用2万，术前检查和术后复查另算，总共约2.5万"},
			},
		},
		{
			ID:              "rule-014",
			Code:            "price.on_site",
			Name:            "规则4.3：到店加价",
			Category:        "price_fraud",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "电话低价，到店加价"},
			Description:     "电话和到店报价不一致，属于典型价格误导。",
			LegalBasis:      "《价格法》第十四条关于虚假价格宣传的要求。",
			SuggestedScript: "种植牙根据材料不同，价格从5000到2万不等，建议您来院详细了解。",
			Examples: RuleExamples{
				Risky: []string{"电话：种植牙5000一颗；到店：5000是最便宜的材料，建议用2万的"},
				Safe:  []string{"电话：种植牙根据材料不同，价格从5000到2万不等，建议您来院详细了解"},
			},
		},
		{
			ID:              "rule-015",
			Code:            "scope.cross_department",
			Name:            "规则5.1：跨科室执业",
			Category:        "beyond_scope",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "不在执业范围 + 我也能做"},
			Description:     "跨注册范围承诺诊疗能力。",
			LegalBasis:      "《执业医师法》第十四条关于执业范围的要求。",
			SuggestedScript: "这个不在我的执业范围，我帮您联系眼科医生。",
			Examples: RuleExamples{
				Risky: []string{"口腔科医生：我也会做双眼皮，来找我吧", "眼科医生：我也能看牙，顺便给你看看"},
				Safe:  []string{"这个不在我的执业范围，我帮您联系眼科医生", "这个需要口腔科医生来看，我给您转诊"},
			},
		},
		{
			ID:              "rule-016",
			Code:            "scope.untrained_tech",
			Name:            "规则5.2：未经培训使用新技术",
			Category:        "beyond_scope",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "新技术/新设备 + 未经培训"},
			Description:     "未经培训或授权，擅自宣称可使用新技术。",
			LegalBasis:      "《执业医师法》及医疗质量安全相关要求。",
			SuggestedScript: "这个新技术我们医院有，由专门的医生负责。",
			Examples: RuleExamples{
				Risky: []string{"这个新技术我也能做"},
				Safe:  []string{"这个新技术我们医院有，由专门的医生负责"},
			},
		},
		{
			ID:              "rule-017",
			Code:            "other.degrade",
			Name:            "规则6.1：诋毁同行",
			Category:        "other",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"别的医院", "不行", "太差"}, "operator": "OR"},
			Description:     "贬低其他医院或医生，诱导排他性选择。",
			LegalBasis:      "医疗宣传与诚信经营规范。",
			SuggestedScript: "我们在这方面有丰富经验。",
			Examples: RuleExamples{
				Risky: []string{"别的医院都不行，只有我们能做", "XX医院的医生水平太差了"},
				Safe:  []string{"我们在这方面有丰富经验", "不同医院各有特点"},
			},
		},
		{
			ID:              "rule-018",
			Code:            "other.privacy",
			Name:            "规则6.2：泄露患者隐私",
			Category:        "other",
			Scope:           "content",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "公开患者姓名/身份/照片"},
			Description:     "未经同意公开患者信息或影像，侵犯隐私。",
			LegalBasis:      "患者隐私保护与医疗信息管理要求。",
			SuggestedScript: "有位患者上周在我们这做了...",
			Examples: RuleExamples{
				Risky: []string{"李女士（35岁，XX公司职员）上周在我们这做了...", "展示患者照片，未打码"},
				Safe:  []string{"有位患者上周在我们这做了...", "展示患者照片，面部打码"},
			},
		},
		{
			ID:              "rule-019",
			Code:            "other.honor_fake",
			Name:            "规则6.3：虚假宣传荣誉",
			Category:        "other",
			Scope:           "content",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "虚构荣誉/资质"},
			Description:     "虚构医院等级、医生资质或其他荣誉。",
			LegalBasis:      "医疗宣传与诚信经营规范。",
			SuggestedScript: "如实告知医院等级和医生资质。",
			Examples: RuleExamples{
				Risky: []string{"我们是三甲医院", "我们医生是中华医学会会员"},
				Safe:  []string{"如实告知医院等级和医生资质"},
			},
		},
	}
}
