package compliance

type builtinRuleSeed struct {
	ID              string
	Code            string
	Name            string
	Category        string
	Scope           string
	Severity        string
	TriggerType     string
	Conditions      JSONMap
	Description     string
	LegalBasis      string
	SuggestedScript string
	Examples        RuleExamples
}

type emrRuleObjectOptions struct {
	Executor      string
	TargetType    string
	TargetPath    string
	Fields        []string
	Stages        []string
	Severity      string
	BlockSubmit   bool
	BlockArchive  bool
	AllowConfirm  bool
	CountInQC     bool
	EvidenceTypes []string
	LogicType     string
}

func emrRuleObjectConditions(opts emrRuleObjectOptions) JSONMap {
	logicType := opts.LogicType
	if logicType == "" {
		logicType = opts.Executor + "_rule"
	}
	return JSONMap{
		"type":      "emr_rule_definition",
		"target":    JSONMap{"type": opts.TargetType, "path": opts.TargetPath},
		"execution": JSONMap{"executor": opts.Executor, "stages": opts.Stages},
		"logic": JSONMap{
			"operator":   "ALL",
			"conditions": []JSONMap{{"type": logicType, "fields": opts.Fields}},
		},
		"action": JSONMap{
			"severity":      opts.Severity,
			"block_submit":  opts.BlockSubmit,
			"block_archive": opts.BlockArchive,
			"allow_confirm": opts.AllowConfirm,
			"count_in_qc":   opts.CountInQC,
		},
		"evidence_schema": JSONMap{"types": opts.EvidenceTypes, "fields": opts.Fields},
		"messages":        JSONMap{"doctor_style": "short_actionable", "qc_style": "evidence_first"},
	}
}

type emrHardRuleOptions struct {
	TargetType    string
	TargetPath    string
	Fields        []string
	Stages        []string
	Severity      string
	BlockSubmit   bool
	BlockArchive  bool
	AllowConfirm  bool
	CountInQC     bool
	EvidenceTypes []string
}

func emrHardRuleConditions(opts emrHardRuleOptions) JSONMap {
	return JSONMap{
		"type": "emr_rule_definition",
		"target": JSONMap{
			"type": opts.TargetType,
			"path": opts.TargetPath,
		},
		"execution": JSONMap{
			"executor": "hard",
			"stages":   opts.Stages,
		},
		"logic": JSONMap{
			"operator": "ALL",
			"conditions": []JSONMap{
				{
					"type":   "hard_rule",
					"fields": opts.Fields,
				},
			},
		},
		"action": JSONMap{
			"severity":      opts.Severity,
			"block_submit":  opts.BlockSubmit,
			"block_archive": opts.BlockArchive,
			"allow_confirm": opts.AllowConfirm,
			"count_in_qc":   opts.CountInQC,
		},
		"evidence_schema": JSONMap{
			"types":  opts.EvidenceTypes,
			"fields": opts.Fields,
		},
		"messages": JSONMap{
			"doctor_style": "short_actionable",
			"qc_style":     "evidence_first",
		},
	}
}

func builtinRuleSeeds() []builtinRuleSeed {
	return []builtinRuleSeed{
		{
			ID:              "rule-001",
			Code:            "guarantee.direct",
			Name:            "规则1.1：直接保证",
			Category:        "guarantee",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"保证", "治愈", "治好", "康复", "恢复", "痊愈"}, "operator": "AND"},
			Description:     "直接对诊疗效果作出保证性承诺，属于第一优先级风险。",
			LegalBasis:      "《医疗广告管理办法》第七条：不得对诊疗效果作出保证性承诺。",
			SuggestedScript: "成功率较高，但因个体差异，不能保证一定达到某个结果。",
			Examples: RuleExamples{
				Risky: []string{"我保证你一定能治好", "保证你术后视力能恢复到1.5", "我们保证种植后20年不会掉"},
				Safe:  []string{"成功率在95%以上，但因个体差异，不能保证", "大多数患者术后视力可以恢复到1.2-1.5", "如果按医嘱护理，用20年问题不大，但不能保证"},
			},
		},
		{
			ID:              "rule-002",
			Code:            "guarantee.implied",
			Name:            "规则1.2：暗示保证",
			Category:        "guarantee",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "一定|肯定|绝对|必然 + 能|会 + 治好|康复|恢复"},
			Description:     "使用绝对化表达，构成变相保证。",
			LegalBasis:      "《医疗广告管理办法》第七条：不得含有保证性承诺内容。",
			SuggestedScript: "有较大概率恢复，但仍需根据检查结果和个体差异判断。",
			Examples: RuleExamples{
				Risky: []string{"你这个一定能治好", "肯定会恢复的", "绝对能看到1.5"},
				Safe:  []string{"有很大概率能治好，但不能说一定", "大多数情况下会恢复，但也有个体差异", "我们会尽力帮你恢复视力"},
			},
		},
		{
			ID:              "rule-003",
			Code:            "guarantee.case",
			Name:            "规则1.3：案例保证",
			Category:        "guarantee",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "成功案例 + 你也会一样/一样的/肯定"},
			Description:     "讲述其他患者的成功案例并暗示个体结果一致，构成变相保证。",
			LegalBasis:      "医疗广告与诊疗沟通规范，不得通过个案暗示普遍效果。",
			SuggestedScript: "上个月张女士术后恢复得不错，但每个人情况不同。",
			Examples: RuleExamples{
				Risky: []string{"上个月张女士做完，现在1.5，你也会一样的", "我们做过800例，没一个失败的，你放心"},
				Safe:  []string{"上个月张女士术后恢复得不错，但每个人情况不同", "我们做过800例，成功率很高，但不能说100%成功"},
			},
		},
		{
			ID:              "rule-004",
			Code:            "guarantee.duration",
			Name:            "规则1.4：承诺维持时间",
			Category:        "guarantee",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"一辈子", "20年", "终身", "永久"}, "operator": "OR"},
			Description:     "承诺具体维持时间或永久有效，属于风险承诺。",
			LegalBasis:      "医疗广告与诊疗沟通规范，不得对长期效果作绝对承诺。",
			SuggestedScript: "如果护理得当，种植牙可以用很多年，有患者用了20年以上。",
			Examples: RuleExamples{
				Risky: []string{"种植牙能用一辈子", "保证20年不会掉", "做完ICL终身有效"},
				Safe:  []string{"如果护理得当，种植牙可以用很多年，有患者用了20年以上", "ICL晶体理论上可以长期使用，但也可能因某些原因需要取出"},
			},
		},
		{
			ID:              "rule-005",
			Code:            "misleading.exaggerate",
			Name:            "规则2.1：夸大疗效",
			Category:        "misleading",
			Scope:           "communication",
			Severity:        "medium",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"最好", "最佳", "唯一", "独家"}, "operator": "OR"},
			Description:     "使用绝对化或夸张性描述推广方案，容易误导患者。",
			LegalBasis:      "《医疗广告管理办法》与《反不正当竞争法》关于虚假或引人误解宣传的要求。",
			SuggestedScript: "这是目前常用的治疗方案之一。",
			Examples: RuleExamples{
				Risky: []string{"这是最好的治疗方案", "唯一能治愈的方法", "我们是全国唯一引进这个设备的"},
				Safe:  []string{"这是目前常用的治疗方案之一", "这个方法效果不错，但也有其他选择", "我们引进了这个设备，在本地区较为先进"},
			},
		},
		{
			ID:              "rule-006",
			Code:            "misleading.degrade",
			Name:            "规则2.2：贬低其他方案",
			Category:        "misleading",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "别的医院/方案/医生 + 不行/骗人/差"},
			Description:     "贬低其他医院、方案或医生，诱导患者排他性选择。",
			LegalBasis:      "《医疗广告管理办法》及诚信宣传要求。",
			SuggestedScript: "我们在这方面有丰富经验，但其他医院也有各自的优势。",
			Examples: RuleExamples{
				Risky: []string{"别的医院都不行，只有我们能做", "传统方法效果差，都是骗人的", "那家医院的设备太老了"},
				Safe:  []string{"我们在这方面有丰富经验，但其他医院也有各自的优势", "传统方法也有效果，只是我们这个方法更先进一些", "不同医院的设备配置不同，各有特点"},
			},
		},
		{
			ID:              "rule-007",
			Code:            "misleading.urgency",
			Name:            "规则2.3：制造紧迫感",
			Category:        "misleading",
			Scope:           "communication",
			Severity:        "medium",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"今天不做", "明天就涨价", "只剩", "下个月", "排队半年"}, "operator": "OR"},
			Description:     "通过优惠、名额或排队时长制造不必要的紧迫感。",
			LegalBasis:      "医疗服务宣传与消费者权益保护相关要求。",
			SuggestedScript: "我们目前有优惠活动，具体可以咨询前台。",
			Examples: RuleExamples{
				Risky: []string{"今天不做，明天就涨价了", "现在只剩3个名额了", "这个月不做，下个月就要排队半年"},
				Safe:  []string{"我们目前有优惠活动，具体可以咨询前台", "近期预约的患者比较多，建议您尽早决定", "医生的档期比较满，建议提前预约"},
			},
		},
		{
			ID:              "rule-008",
			Code:            "misleading.data",
			Name:            "规则2.4：虚假数据",
			Category:        "misleading",
			Scope:           "content",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "满意度/无事故/万例 + 无法验证"},
			Description:     "使用无法验证的数据或缺乏证据支撑的统计结论。",
			LegalBasis:      "《反不正当竞争法》第八条关于虚假或引人误解宣传的要求。",
			SuggestedScript: "大多数患者对手术效果比较满意。",
			Examples: RuleExamples{
				Risky: []string{"我们的患者满意度98%", "万例手术无一例事故"},
				Safe:  []string{"大多数患者对手术效果比较满意", "我们非常重视手术安全，有完善的质控流程"},
			},
		},
		{
			ID:              "rule-009",
			Code:            "fear.severity",
			Name:            "规则3.1：夸大病情",
			Category:        "fear_mongering",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"很严重", "非常危险", "再不做就来不及了", "拖不得"}, "operator": "OR"},
			Description:     "通过夸大风险推动患者快速决策。",
			LegalBasis:      "医疗服务宣传和消费者保护要求，禁止利用恐惧进行误导。",
			SuggestedScript: "病情需要及时处理，但具体风险和时间判断应基于检查结果说明。",
			Examples: RuleExamples{
				Risky: []string{"你这个很严重，再不做就瞎了", "这个必须马上手术，否则会恶化", "你这个拖不得，再拖就完了"},
				Safe:  []string{"您的白内障已到中期，建议尽快手术，以免影响日常生活", "这个病情需要及时治疗，但也不用过度紧张", "建议您尽早手术，但具体时间可以和医生商量"},
			},
		},
		{
			ID:              "rule-010",
			Code:            "fear.panic",
			Name:            "规则3.2：制造恐慌",
			Category:        "fear_mongering",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "不做 + 最后全掉光/失明/严重后果"},
			Description:     "通过描述严重后果制造恐慌。",
			LegalBasis:      "医疗服务宣传和消费者保护要求，禁止利用恐惧进行误导。",
			SuggestedScript: "缺牙后，邻牙可能会移位，建议考虑种植修复。",
			Examples: RuleExamples{
				Risky: []string{"不种牙的话，其他牙齿也会松动，最后全掉光", "近视不矫正，度数会越来越深，最后会失明"},
				Safe:  []string{"缺牙后，邻牙可能会移位，建议考虑种植修复", "近视度数可能会加深，建议定期检查"},
			},
		},
		{
			ID:              "rule-011",
			Code:            "fear.compare",
			Name:            "规则3.3：对比渲染",
			Category:        "fear_mongering",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "做了你就能...；不做你就..."},
			Description:     "对比做与不做的后果，夸大不做的负面结果。",
			LegalBasis:      "医疗服务宣传和消费者保护要求，禁止利用对比渲染制造压力。",
			SuggestedScript: "手术后视力会有改善，但也可以选择继续戴眼镜，这是您的个人选择。",
			Examples: RuleExamples{
				Risky: []string{"做了，你就能看得清清楚楚；不做，你就要戴一辈子眼镜，还会越来越深"},
				Safe:  []string{"手术后视力会有改善，但也可以选择继续戴眼镜，这是您的个人选择"},
			},
		},
		{
			ID:              "rule-012",
			Code:            "price.fake_original",
			Name:            "规则4.1：虚假原价",
			Category:        "price_fraud",
			Scope:           "content",
			Severity:        "critical",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"原价", "现在优惠", "市场价"}, "operator": "OR"},
			Description:     "先报高价再说优惠，或者虚构市场价。",
			LegalBasis:      "《价格法》第十四条关于虚构原价、虚假优惠折价的要求。",
			SuggestedScript: "我们的价格是2万，目前有优惠活动。",
			Examples: RuleExamples{
				Risky: []string{"原价3万，现在活动价1.5万", "市场价5万，我们只要2万"},
				Safe:  []string{"我们的价格是2万，目前有优惠活动", "不同医院的价格不同，我们的价格在XX元左右"},
			},
		},
		{
			ID:              "rule-013",
			Code:            "price.hidden_fee",
			Name:            "规则4.2：隐瞒费用",
			Category:        "price_fraud",
			Scope:           "content",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "只说部分费用，隐瞒其他费用"},
			Description:     "只说局部费用，不披露总费用构成。",
			LegalBasis:      "《价格法》第十四条及消费告知规范。",
			SuggestedScript: "种植体费用1万，加上牙冠和其他费用，总计约1.5-2万。",
			Examples: RuleExamples{
				Risky: []string{"种植牙1万一颗", "ICL手术2万"},
				Safe:  []string{"种植体费用1万，加上牙冠和其他费用，总计约1.5-2万", "手术费用2万，术前检查和术后复查另算，总共约2.5万"},
			},
		},
		{
			ID:              "rule-014",
			Code:            "price.on_site",
			Name:            "规则4.3：到店加价",
			Category:        "price_fraud",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "电话低价，到店加价"},
			Description:     "电话和到店报价不一致，属于典型价格误导。",
			LegalBasis:      "《价格法》第十四条关于虚假价格宣传的要求。",
			SuggestedScript: "种植牙根据材料不同，价格从5000到2万不等，建议您来院详细了解。",
			Examples: RuleExamples{
				Risky: []string{"电话：种植牙5000一颗；到店：5000是最便宜的材料，建议用2万的"},
				Safe:  []string{"电话：种植牙根据材料不同，价格从5000到2万不等，建议您来院详细了解"},
			},
		},
		{
			ID:              "rule-015",
			Code:            "scope.cross_department",
			Name:            "规则5.1：跨科室执业",
			Category:        "beyond_scope",
			Scope:           "communication",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "不在执业范围 + 我也能做"},
			Description:     "跨注册范围承诺诊疗能力。",
			LegalBasis:      "《执业医师法》第十四条关于执业范围的要求。",
			SuggestedScript: "这个不在我的执业范围，我帮您联系眼科医生。",
			Examples: RuleExamples{
				Risky: []string{"口腔科医生：我也会做双眼皮，来找我吧", "眼科医生：我也能看牙，顺便给你看看"},
				Safe:  []string{"这个不在我的执业范围，我帮您联系眼科医生", "这个需要口腔科医生来看，我给您转诊"},
			},
		},
		{
			ID:              "rule-016",
			Code:            "scope.untrained_tech",
			Name:            "规则5.2：未经培训使用新技术",
			Category:        "beyond_scope",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "新技术/新设备 + 未经培训"},
			Description:     "未经培训或授权，擅自宣称可使用新技术。",
			LegalBasis:      "《执业医师法》及医疗质量安全相关要求。",
			SuggestedScript: "这个新技术我们医院有，由专门的医生负责。",
			Examples: RuleExamples{
				Risky: []string{"这个新技术我也能做"},
				Safe:  []string{"这个新技术我们医院有，由专门的医生负责"},
			},
		},
		{
			ID:              "rule-017",
			Code:            "other.degrade",
			Name:            "规则6.1：诋毁同行",
			Category:        "other",
			Scope:           "communication",
			Severity:        "high",
			TriggerType:     "keywords",
			Conditions:      JSONMap{"type": "keywords", "keywords": []string{"别的医院", "不行", "太差"}, "operator": "OR"},
			Description:     "贬低其他医院或医生，诱导排他性选择。",
			LegalBasis:      "医疗宣传与诚信经营规范。",
			SuggestedScript: "我们在这方面有丰富经验。",
			Examples: RuleExamples{
				Risky: []string{"别的医院都不行，只有我们能做", "XX医院的医生水平太差了"},
				Safe:  []string{"我们在这方面有丰富经验", "不同医院各有特点"},
			},
		},
		{
			ID:              "rule-018",
			Code:            "other.privacy",
			Name:            "规则6.2：泄露患者隐私",
			Category:        "other",
			Scope:           "content",
			Severity:        "critical",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "公开患者姓名/身份/照片"},
			Description:     "未经同意公开患者信息或影像，侵犯隐私。",
			LegalBasis:      "患者隐私保护与医疗信息管理要求。",
			SuggestedScript: "有位患者上周在我们这做了...",
			Examples: RuleExamples{
				Risky: []string{"李女士（35岁，XX公司职员）上周在我们这做了...", "展示患者照片，未打码"},
				Safe:  []string{"有位患者上周在我们这做了...", "展示患者照片，面部打码"},
			},
		},
		{
			ID:              "rule-019",
			Code:            "other.honor_fake",
			Name:            "规则6.3：虚假宣传荣誉",
			Category:        "other",
			Scope:           "content",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      JSONMap{"type": "semantic", "expression": "虚构荣誉/资质"},
			Description:     "虚构医院等级、医生资质或其他荣誉。",
			LegalBasis:      "医疗宣传与诚信经营规范。",
			SuggestedScript: "如实告知医院等级和医生资质。",
			Examples: RuleExamples{
				Risky: []string{"我们是三甲医院", "我们医生是中华医学会会员"},
				Safe:  []string{"如实告知医院等级和医生资质"},
			},
		},
		{
			ID:              "emr-rule-001",
			Code:            "common.visible_fields",
			Name:            "公共字段必显",
			Category:        "emr_template",
			Scope:           "emr",
			Severity:        "low",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "template", TargetPath: "schema.common_fields", Fields: []string{"chief_complaint", "present_illness", "physical_exam", "diagnosis", "medical_advice"}, Stages: []string{"template_publish"}, Severity: "blocking", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "所有模板必须保留主诉、现病史、体格检查、诊断、医嘱等公共字段位置。",
			LegalBasis:      "门急诊病历模板设计规范。",
			SuggestedScript: "所有模板必须保留公共字段位置。",
			Examples:        RuleExamples{Safe: []string{"标准全科门诊病历"}},
		},
		{
			ID:              "emr-rule-002",
			Code:            "common.orders_split",
			Name:            "处方与处置分离",
			Category:        "emr_template",
			Scope:           "emr",
			Severity:        "low",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "structured", TargetType: "template", TargetPath: "schema.orders", Fields: []string{"prescription", "treatment", "medical_advice"}, Stages: []string{"template_publish", "pre_submit"}, Severity: "blocking", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field", "structured_object"}}),
			Description:     "药品处方和治疗/收费相关项目必须分开建模与展示。",
			LegalBasis:      "门急诊病历模板设计规范。",
			SuggestedScript: "处方和处置应分开展示。",
			Examples:        RuleExamples{Safe: []string{"处方", "处置"}},
		},
		{
			ID:              "emr-rule-003",
			Code:            "gynecology.history",
			Name:            "适龄女性自动显隐",
			Category:        "emr_template",
			Scope:           "emr",
			Severity:        "low",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "template", TargetPath: "extensions.gynecology", Fields: []string{"menstrual_history", "marriage_childbearing", "pregnancy_history", "gyne_exam"}, Stages: []string{"template_publish"}, Severity: "blocking", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "妇科扩展字段默认展示；其他模板只有在适龄女性规则命中时才做提醒，不直接显现。",
			LegalBasis:      "门急诊病历模板设计规范。",
			SuggestedScript: "妇科扩展字段按模板和人群条件控制。",
			Examples:        RuleExamples{Safe: []string{"月经史", "孕产史"}},
		},
		{
			ID:              "emr-rule-004",
			Code:            "gynecology.exam",
			Name:            "妇科查体挂接体格检查",
			Category:        "emr_template",
			Scope:           "emr",
			Severity:        "low",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "template", TargetPath: "sections.physical_exam.gyne_exam", Fields: []string{"physical_exam", "gyne_exam"}, Stages: []string{"template_publish"}, Severity: "blocking", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "妇科专科查体仍属于体格检查体系，不单独替代体格检查主段落。",
			LegalBasis:      "门急诊病历模板设计规范。",
			SuggestedScript: "妇科专科查体应挂接到体格检查。",
			Examples:        RuleExamples{Safe: []string{"妇科专科查体"}},
		},
		{
			ID:              "emr-rule-005",
			Code:            "tcm.dual_diagnosis",
			Name:            "西医/中医诊断并存",
			Category:        "emr_template",
			Scope:           "emr",
			Severity:        "low",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "template", TargetPath: "sections.diagnosis", Fields: []string{"diagnosis", "tcm_diagnosis"}, Stages: []string{"template_publish"}, Severity: "blocking", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "公共字段中的诊断保留统一入口，中医诊断作为扩展字段并存。",
			LegalBasis:      "门急诊病历模板设计规范。",
			SuggestedScript: "中医诊断作为扩展字段并存。",
			Examples:        RuleExamples{Safe: []string{"中医诊断", "西医诊断"}},
		},
		{
			ID:              "emr-rule-006",
			Code:            "tcm.formula",
			Name:            "方药仍归处方体系",
			Category:        "emr_template",
			Scope:           "emr",
			Severity:        "low",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "structured", TargetType: "template", TargetPath: "structured.formula", Fields: []string{"formula", "prescription"}, Stages: []string{"template_publish"}, Severity: "blocking", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field", "structured_object"}}),
			Description:     "中药方药可以扩展展示，但结构上仍归入处方/方药对象。",
			LegalBasis:      "门急诊病历模板设计规范。",
			SuggestedScript: "方药应归入处方体系。",
			Examples:        RuleExamples{Safe: []string{"方药"}},
		},
		{
			ID:              "emr-rule-007",
			Code:            "dental.tooth_position",
			Name:            "牙位绑定诊断与处置",
			Category:        "emr_template",
			Scope:           "emr",
			Severity:        "low",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "structured", TargetType: "template", TargetPath: "structured.tooth_position", Fields: []string{"tooth_position", "diagnosis", "treatment_plan"}, Stages: []string{"template_publish"}, Severity: "blocking", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field", "structured_object"}}),
			Description:     "牙位字段必须能解释诊断、影像和治疗计划。",
			LegalBasis:      "门急诊病历模板设计规范。",
			SuggestedScript: "牙位字段应绑定诊断与处置。",
			Examples:        RuleExamples{Safe: []string{"牙位"}},
		},
		{
			ID:              "emr-rule-008",
			Code:            "dental.exam",
			Name:            "口腔专科查体挂接体格检查",
			Category:        "emr_template",
			Scope:           "emr",
			Severity:        "low",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "template", TargetPath: "sections.physical_exam.dental_exam", Fields: []string{"physical_exam", "dental_exam"}, Stages: []string{"template_publish"}, Severity: "blocking", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "口腔专科检查作为专科查体扩展，不脱离体格检查主段落。",
			LegalBasis:      "门急诊病历模板设计规范。",
			SuggestedScript: "口腔专科检查应挂接到体格检查。",
			Examples:        RuleExamples{Safe: []string{"口腔专科检查"}},
		},
		{
			ID:              "emr-rule-009",
			Code:            "pediatrics.guardian_block",
			Name:            "监护人字段固定扩展",
			Category:        "emr_template",
			Scope:           "emr",
			Severity:        "low",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "template", TargetPath: "extensions.guardian", Fields: []string{"guardian", "feeding", "growth", "vaccination"}, Stages: []string{"template_publish"}, Severity: "blocking", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "儿科模板必须固定提供监护人、喂养史、生长发育、疫苗接种等扩展字段。",
			LegalBasis:      "儿科门急诊病历模板结构要求。",
			SuggestedScript: "儿科模板缺少监护人或生长发育相关字段，请补齐后发布。",
			Examples:        RuleExamples{Risky: []string{"儿科模板缺少监护人字段"}, Safe: []string{"监护人、喂养史、生长发育、疫苗接种字段完整"}},
		},
		{
			ID:              "emr-rule-101",
			Code:            "emr.patient.basic_info",
			Name:            "患者基本信息完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrHardRuleConditions(emrHardRuleOptions{TargetType: "record", TargetPath: "patient", Fields: []string{"patient.name", "patient.gender", "patient.age_text", "patient.phone", "patient.allergy_history"}, Stages: []string{"save", "pre_submit", "pre_archive"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "姓名、性别、出生年月、民族、婚姻、职业、单位、住址、药物过敏史，以及每页姓名、病历号、就诊日期、科别必须完整。",
			LegalBasis:      "门诊病历质量评定标准：一般项目。",
			SuggestedScript: "请补全患者基本信息和药物过敏史后再提交。",
			Examples:        RuleExamples{Risky: []string{"过敏史写“无”但无问诊证据"}, Safe: []string{"患者信息完整，过敏史有问诊确认"}},
		},
		{
			ID:              "emr-rule-101a",
			Code:            "emr.time.consistency",
			Name:            "病历时间一致性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrHardRuleConditions(emrHardRuleOptions{TargetType: "record", TargetPath: "time_chain", Fields: []string{"encountered_at", "created_at", "updated_at", "archived_at"}, Stages: []string{"save", "pre_submit", "pre_archive", "post_archive_qc"}, Severity: "blocking", BlockSubmit: true, BlockArchive: true, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field", "calculation"}}),
			Description:     "接诊开始时间、结束时间、病历创建时间、提交时间、归档时间、最后修改时间不得逆序或异常。",
			LegalBasis:      "门诊病历时间一致性与可追溯性要求。",
			SuggestedScript: "请检查病历时间链是否完整、是否存在逆序。",
			Examples:        RuleExamples{Risky: []string{"提交时间早于创建时间"}, Safe: []string{"时间链完整且顺序正确"}},
		},
		{
			ID:              "emr-rule-102",
			Code:            "emr.chief_complaint.norm",
			Name:            "主诉规范性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrHardRuleConditions(emrHardRuleOptions{TargetType: "field", TargetPath: "sections.chief_complaint", Fields: []string{"sections.chief_complaint"}, Stages: []string{"realtime", "save", "pre_submit", "pre_archive"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "text_excerpt"}}),
			Description:     "主诉应为主要症状、部位和持续时间，重点突出、简明扼要；复诊无新症状且诊断明确时可写“病史同前”；主诉不得超过20个字（含标点）。",
			LegalBasis:      "门诊病历质量评定标准：主诉。",
			SuggestedScript: "请把主诉写成症状、部位和持续时间，不要用诊断名称代替。",
			Examples:        RuleExamples{Risky: []string{"主诉仅写“上感”"}, Safe: []string{"发热3天，伴咽痛"}},
		},
		{
			ID:              "emr-rule-103",
			Code:            "emr.present_illness.complete",
			Name:            "现病史与相关病史完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "llm", TargetType: "field", TargetPath: "sections.present_illness", Fields: []string{"sections.present_illness", "sections.chief_complaint", "sections.diagnosis"}, Stages: []string{"save", "pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "text_excerpt", "model_explanation"}}),
			Description:     "初诊记录起病、演变、主要症状、诊疗经过和效果；复诊记录治疗后变化、疗效、未确诊时的新症状和鉴别资料。相关既往史、婚育史、过敏史、家族史不能缺。",
			LegalBasis:      "门诊病历质量评定标准：病史。",
			SuggestedScript: "请围绕主诉补全现病史，并确认过敏史、既往史等关键病史。",
			Examples:        RuleExamples{Risky: []string{"现病史只重复主诉"}, Safe: []string{"记录起病演变、伴随症状和过敏史"}},
		},
		{
			ID:              "emr-rule-103a",
			Code:            "emr.past_history.complete",
			Name:            "既往史完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field", TargetPath: "sections.past_history", Fields: []string{"sections.past_history"}, Stages: []string{"save", "pre_submit", "pre_archive"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "慢性病史、手术史、外伤史、传染病史、既往同类疾病、既往治疗情况应按场景采集。",
			LegalBasis:      "门诊病历质量评定标准：既往史。",
			SuggestedScript: "请补充既往史；如无特殊情况，也需有问诊或确认依据。",
			Examples:        RuleExamples{Risky: []string{"慢病复诊无既往史"}, Safe: []string{"既往史记录完整"}},
		},
		{
			ID:              "emr-rule-103b",
			Code:            "emr.personal_history.complete",
			Name:            "个人史完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field", TargetPath: "sections.personal_history", Fields: []string{"sections.personal_history"}, Stages: []string{"save", "pre_submit"}, Severity: "notice", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "吸烟、饮酒、职业暴露、生活习惯等个人史应在相关场景采集。",
			LegalBasis:      "门诊病历质量评定标准：个人史。",
			SuggestedScript: "请补充个人史，或确认本次不适用。",
			Examples:        RuleExamples{Risky: []string{"长期空白且无说明"}, Safe: []string{"个人史已记录或说明不适用"}},
		},
		{
			ID:              "emr-rule-103c",
			Code:            "emr.family_history.complete",
			Name:            "家族史完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field", TargetPath: "sections.family_history", Fields: []string{"sections.family_history"}, Stages: []string{"save", "pre_submit"}, Severity: "notice", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "遗传病、肿瘤、慢病等家族史在相关场景下应记录。",
			LegalBasis:      "门诊病历质量评定标准：家族史。",
			SuggestedScript: "请补充家族史，或确认无相关家族病史。",
			Examples:        RuleExamples{Risky: []string{"相关病种场景缺家族史"}, Safe: []string{"家族史已记录"}},
		},
		{
			ID:              "emr-rule-104",
			Code:            "emr.present_illness.general_status",
			Name:            "饮食睡眠二便体重补问",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field_group", TargetPath: "structured.general_status", Fields: []string{"diet", "sleep", "bowel_movement", "urination", "recent_weight_change"}, Stages: []string{"save", "pre_submit"}, Severity: "notice", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "现病史补全应覆盖饮食、睡眠、大便、小便和近期体重变化，尤其服务慢病评估、中医辨证和基层全科。",
			LegalBasis:      "门诊病历质量评定标准：病史资料完整性。",
			SuggestedScript: "请补问饮食、睡眠、二便和近期体重变化，或确认本次不适用。",
			Examples:        RuleExamples{Risky: []string{"全程未问饮食睡眠二便"}, Safe: []string{"已记录饮食睡眠及二便情况"}},
		},
		{
			ID:              "emr-rule-105",
			Code:            "emr.physical_exam.specific",
			Name:            "体格检查具体性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "llm", TargetType: "field", TargetPath: "sections.physical_exam", Fields: []string{"sections.physical_exam", "structured.vital_signs"}, Stages: []string{"save", "pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "text_excerpt", "model_explanation"}}),
			Description:     "体检应记录一般情况、常规项目、与主诉相关的阳性体征、必要阴性体征和专科针对性检查，不能笼统写“正常”。",
			LegalBasis:      "门诊病历质量评定标准：体格检查。",
			SuggestedScript: "请补充生命体征、阳性体征和必要阴性体征，不要只写心肺腹正常。",
			Examples:        RuleExamples{Risky: []string{"心肺腹正常"}, Safe: []string{"记录血压、阳性体征和必要阴性体征"}},
		},
		{
			ID:              "emr-rule-106",
			Code:            "emr.auxiliary_exam.closed_loop",
			Name:            "辅助检查结果闭环",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "structured", TargetType: "relationship", TargetPath: "orders.exams,sections.auxiliary_exam", Fields: []string{"sections.auxiliary_exam", "structured.exam_orders", "structured.exam_results"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "structured_object"}}),
			Description:     "必要辅助检查和专科检查需记录，已有检查结果应进入病历；外院报告支持上传并由医生确认入文。",
			LegalBasis:      "门诊病历质量评定标准：辅助检查。",
			SuggestedScript: "请把已有检查结果写入病历，或标明结果待回。",
			Examples:        RuleExamples{Risky: []string{"已开检查但无结果或待回说明"}, Safe: []string{"检查结果已入文或已注明待回"}},
		},
		{
			ID:              "emr-rule-107",
			Code:            "emr.diagnosis.plan",
			Name:            "诊断规范与待查计划",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrHardRuleConditions(emrHardRuleOptions{TargetType: "field", TargetPath: "sections.diagnosis", Fields: []string{"sections.diagnosis"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "诊断明确时写完整诊断；诊断不明时写待查并给出进一步检查或处理建议；复诊应记录诊断进展。",
			LegalBasis:      "门诊病历质量评定标准：诊断。",
			SuggestedScript: "请完善诊断名称，或在待查时给出下一步检查计划。",
			Examples:        RuleExamples{Risky: []string{"诊断为空或多次待查无计划"}, Safe: []string{"待查后写明进一步检查建议"}},
		},
		{
			ID:              "emr-rule-107a",
			Code:            "emr.diagnosis.consistency",
			Name:            "诊断与病史查体检查一致性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "llm", TargetType: "relationship", TargetPath: "diagnosis,evidence_chain", Fields: []string{"sections.chief_complaint", "sections.present_illness", "sections.physical_exam", "sections.auxiliary_exam", "sections.diagnosis"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "text_excerpt", "model_explanation"}}),
			Description:     "诊断必须能被主诉、现病史、体格检查、辅助检查解释；明显脱节时命中。",
			LegalBasis:      "门诊病历质量评定标准：诊断依据一致性。",
			SuggestedScript: "请核对诊断是否能被病史、查体和检查结果支持。",
			Examples:        RuleExamples{Risky: []string{"诊断与主诉查体明显不一致"}, Safe: []string{"诊断与病史查体检查一致"}},
		},
		{
			ID:              "emr-rule-108",
			Code:            "emr.treatment.consistency",
			Name:            "处理治疗一致性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "structured", TargetType: "relationship", TargetPath: "diagnosis,prescription,treatment", Fields: []string{"sections.diagnosis", "sections.prescription", "sections.treatment", "sections.medical_advice"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "structured_object"}}),
			Description:     "治疗措施、处方、住院理由、医学证明、特殊检查治疗和重要沟通必须在病历中有对应记录。",
			LegalBasis:      "门诊病历质量评定标准：处理治疗。",
			SuggestedScript: "请核对处方、处置和病历医嘱是否一致。",
			Examples:        RuleExamples{Risky: []string{"有处方但病历无处理意见"}, Safe: []string{"处方与处理意见一致"}},
		},
		{
			ID:              "emr-rule-109",
			Code:            "emr.allergy.required",
			Name:            "过敏史必须确认",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrHardRuleConditions(emrHardRuleOptions{TargetType: "field", TargetPath: "patient.allergy_history", Fields: []string{"patient.allergy_history", "sections.allergy_history"}, Stages: []string{"realtime", "save", "pre_submit", "pre_archive"}, Severity: "blocking", BlockSubmit: false, BlockArchive: true, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "个人史/病史中必须确认药物、食物或其他过敏史；写“无”时也要有问诊证据。",
			LegalBasis:      "门诊病历质量评定标准：一般项目与病史中的药物过敏史。",
			SuggestedScript: "请确认过敏史。若为“无”，需有问诊证据后再提交。",
			Examples:        RuleExamples{Risky: []string{"过敏史为空或无问诊就写无"}, Safe: []string{"已询问并记录青霉素过敏"}},
		},
		{
			ID:              "emr-rule-109a",
			Code:            "emr.allergy.prescription_risk",
			Name:            "过敏史与处方风险一致性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "structured", TargetType: "relationship", TargetPath: "patient.allergy_history,prescription", Fields: []string{"patient.allergy_history", "sections.prescription", "structured.prescription"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "blocking", BlockSubmit: true, BlockArchive: true, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field", "structured_object"}}),
			Description:     "存在明确药物过敏史时，处方不得出现明确风险药物；若使用相关高风险药物，必须有人工确认和风险说明。",
			LegalBasis:      "门诊病历质量评定标准：过敏史与处方安全。",
			SuggestedScript: "请先核对过敏史与处方风险，再继续开药。",
			Examples:        RuleExamples{Risky: []string{"青霉素过敏仍开青霉素类药物"}, Safe: []string{"处方已避开已知过敏药物"}},
		},
		{
			ID:              "emr-rule-110",
			Code:            "emr.tcm.elements",
			Name:            "中医诊疗要素完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "llm", TargetType: "field_group", TargetPath: "tcm.evidence_chain", Fields: []string{"sections.present_illness", "sections.physical_exam", "sections.tcm_diagnosis", "sections.tongue", "sections.pulse_tcm", "sections.syndrome", "sections.treatment_method"}, Stages: []string{"save", "pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "text_excerpt", "model_explanation"}}),
			Description:     "中医病历必须具备中医四诊信息；四诊可写在现病史或体格检查中，并形成辨证、治法、方药/调护建议链条。",
			LegalBasis:      "门诊病历质量评定标准：专科模板与诊断、处理治疗。",
			SuggestedScript: "请补全四诊、舌脉、辨证和治法后再提交。",
			Examples:        RuleExamples{Risky: []string{"只有西医诊断，缺舌脉辨证"}, Safe: []string{"中医诊断、舌脉、辨证、治法完整"}},
		},
		{
			ID:              "emr-rule-110a",
			Code:            "emr.tcm.evidence_chain",
			Name:            "中医四诊证据链",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "llm", TargetType: "relationship", TargetPath: "tcm.four_diagnosis_to_syndrome", Fields: []string{"sections.present_illness", "sections.physical_exam", "sections.tongue", "sections.pulse_tcm", "sections.syndrome", "sections.treatment_method"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "text_excerpt", "model_explanation"}}),
			Description:     "辨证和治法必须能回溯到望闻问切、舌象、脉象等证据；辨证依据为空时命中。",
			LegalBasis:      "中医门诊病历书写与质控要求。",
			SuggestedScript: "请把辨证依据写清楚，至少能回到四诊和舌脉。",
			Examples:        RuleExamples{Risky: []string{"只有辨证结论，没有四诊依据"}, Safe: []string{"四诊证据完整并支持辨证"}},
		},
		{
			ID:              "emr-rule-110b",
			Code:            "emr.tcm.western_diagnosis_prompt",
			Name:            "中医病历西医诊断提示",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field", TargetPath: "sections.diagnosis", Fields: []string{"sections.diagnosis", "sections.tcm_diagnosis"}, Stages: []string{"save", "pre_submit", "post_archive_qc"}, Severity: "notice", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "中医病历应尽量具备西医诊断；无西医诊断时提示，不作为强阻断项。",
			LegalBasis:      "中医门诊病历记录辅助要求。",
			SuggestedScript: "如能明确，请补充西医诊断；如不能明确，至少提示医生当前未写。",
			Examples:        RuleExamples{Risky: []string{"中医病历完全没有任何诊断说明"}, Safe: []string{"中医诊断明确，西医诊断可后补提示"}},
		},
		{
			ID:              "emr-rule-110c",
			Code:            "emr.tcm.formula_consistency",
			Name:            "方药与治法对应",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "llm", TargetType: "relationship", TargetPath: "tcm.treatment_method,formula", Fields: []string{"sections.syndrome", "sections.treatment_method", "sections.formula", "structured.formula"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "text_excerpt", "model_explanation"}}),
			Description:     "方药、加减、煎服法和调护建议必须与辨证、治法一致。",
			LegalBasis:      "中医门诊病历书写与质控要求。",
			SuggestedScript: "请核对方药是否与治法一致。",
			Examples:        RuleExamples{Risky: []string{"寒证却写清热方"}, Safe: []string{"方药与治法一致"}},
		},
		{
			ID:              "emr-rule-111",
			Code:            "emr.signature.required",
			Name:            "医师签名与上级签名",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrHardRuleConditions(emrHardRuleOptions{TargetType: "field", TargetPath: "structured.physician_signature", Fields: []string{"structured.physician_signature", "sections.physician_signature"}, Stages: []string{"pre_archive"}, Severity: "blocking", BlockSubmit: false, BlockArchive: true, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "归档前必须有可识别的医师签名；需要上级签名的文书必须保留上级确认。",
			LegalBasis:      "门诊病历质量评定标准：医师签名。",
			SuggestedScript: "归档前请完成医师确认，必要时补上级签名。",
			Examples:        RuleExamples{Risky: []string{"归档时无医师确认"}, Safe: []string{"归档前已完成医师签名"}},
		},
		{
			ID:              "emr-rule-112",
			Code:            "emr.audit.trail",
			Name:            "修改留痕与书写规范",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "structured", TargetType: "audit_log", TargetPath: "emr_field_events", Fields: []string{"emr_field_events.operator_id", "emr_field_events.change_reason", "emr_field_events.before_value", "emr_field_events.after_value"}, Stages: []string{"post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: false, CountInQC: true, EvidenceTypes: []string{"structured_object"}}),
			Description:     "电子病历归档后修改必须保留原因、修改人、修改时间和前后差异。",
			LegalBasis:      "门诊病历质量评定标准：书写要求。",
			SuggestedScript: "归档后修改请保留原因和前后对比。",
			Examples:        RuleExamples{Risky: []string{"归档后修改无原因"}, Safe: []string{"修改留痕完整"}},
		},
		{
			ID:              "emr-rule-112a",
			Code:            "emr.followup.complete",
			Name:            "复诊安排完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field", TargetPath: "sections.follow_up", Fields: []string{"sections.follow_up"}, Stages: []string{"save", "pre_submit", "pre_archive"}, Severity: "notice", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "需要复诊、观察、待查结果回报、慢病管理的病历必须写明复诊时间、触发条件或随访要求。",
			LegalBasis:      "门诊病历随访与复诊要求。",
			SuggestedScript: "请补充复诊安排或随访条件。",
			Examples:        RuleExamples{Risky: []string{"无复诊安排且病情未闭环"}, Safe: []string{"已写明复诊时间和触发条件"}},
		},
		{
			ID:              "emr-rule-113",
			Code:            "emr.gynecology.menstrual_history",
			Name:            "适龄女性月经史",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field_group", TargetPath: "extensions.gynecology", Fields: []string{"menstrual_history", "last_menstrual_period"}, Stages: []string{"save", "pre_submit", "pre_archive"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "适龄女性接诊需记录月经史，至少包含周期、经期、经量、痛经和末次月经。",
			LegalBasis:      "门诊病历质量评定标准：相关病史。",
			SuggestedScript: "请补充月经史和末次月经后再提交。",
			Examples:        RuleExamples{Risky: []string{"妇科就诊缺月经史"}, Safe: []string{"已记录周期、经期和LMP"}},
		},
		{
			ID:              "emr-rule-113a",
			Code:            "emr.gynecology.marriage_childbearing",
			Name:            "婚育史/孕产史完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field_group", TargetPath: "extensions.gynecology", Fields: []string{"marriage_childbearing", "pregnancy_history"}, Stages: []string{"save", "pre_submit", "pre_archive"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "妇科病历应记录婚育情况、孕次、产次、流产史和避孕情况。",
			LegalBasis:      "门诊病历质量评定标准：相关病史。",
			SuggestedScript: "请补充婚育史和孕产史。",
			Examples:        RuleExamples{Risky: []string{"妇科病历缺婚育史"}, Safe: []string{"婚育史和孕产史完整"}},
		},
		{
			ID:              "emr-rule-113b",
			Code:            "emr.gynecology.exam_required",
			Name:            "妇科查体确认",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field", TargetPath: "sections.gyne_exam", Fields: []string{"sections.gyne_exam", "extensions.gyne_exam_not_done_reason"}, Stages: []string{"pre_submit", "pre_archive"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "腹痛、出血、白带异常、盆腔相关主诉下，应记录妇科专科查体或未查原因。",
			LegalBasis:      "门诊病历质量评定标准：专科查体。",
			SuggestedScript: "请记录妇科查体或说明未查原因。",
			Examples:        RuleExamples{Risky: []string{"妇科主诉存在但无查体"}, Safe: []string{"已记录妇科查体或未查原因"}},
		},
		{
			ID:              "emr-rule-114",
			Code:            "emr.dental.tooth_plan",
			Name:            "牙位与治疗计划对应",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "structured", TargetType: "relationship", TargetPath: "tooth_position,treatment_plan", Fields: []string{"structured.tooth_position", "sections.treatment_plan", "structured.treatment_plan"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "structured_object"}}),
			Description:     "治疗计划必须对应明确牙位，口腔检查、影像和治疗步骤要能互相解释。",
			LegalBasis:      "门诊病历质量评定标准：专科检查与处理治疗。",
			SuggestedScript: "请确认牙位与治疗计划、影像部位一致。",
			Examples:        RuleExamples{Risky: []string{"牙位为空或与治疗计划不一致"}, Safe: []string{"牙位、影像和治疗计划一致"}},
		},
		{
			ID:              "emr-rule-114a",
			Code:            "emr.dental.informed_consent",
			Name:            "口腔操作知情告知",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "structured", TargetType: "relationship", TargetPath: "treatment_plan,informed_consent", Fields: []string{"sections.treatment_plan", "structured.treatment_plan", "sections.informed_consent", "structured.informed_consent"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "structured_object"}}),
			Description:     "拔牙、种植、正畸、修复等操作应记录告知、同意和操作过程。",
			LegalBasis:      "门诊病历质量评定标准：特殊操作记录。",
			SuggestedScript: "请补充知情告知和同意记录。",
			Examples:        RuleExamples{Risky: []string{"有操作计划但无告知记录"}, Safe: []string{"已记录告知与同意"}},
		},
		{
			ID:              "emr-rule-115",
			Code:            "emr.pediatrics.guardian_info",
			Name:            "监护人信息完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrHardRuleConditions(emrHardRuleOptions{TargetType: "field", TargetPath: "patient.guardian", Fields: []string{"patient.guardian", "structured.guardian", "extensions.guardian"}, Stages: []string{"realtime", "save", "pre_submit", "pre_archive"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "陪诊监护人身份、与患儿关系应记录完整。",
			LegalBasis:      "儿科门诊病历要求。",
			SuggestedScript: "请补充监护人信息。",
			Examples:        RuleExamples{Risky: []string{"儿科就诊无监护人信息"}, Safe: []string{"监护人身份和关系完整"}},
		},
		{
			ID:              "emr-rule-116",
			Code:            "emr.pediatrics.fever_peak",
			Name:            "儿童发热峰值记录",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field_group", TargetPath: "extensions.pediatrics_fever", Fields: []string{"temperature", "fever_duration", "antipyretic", "mental_status"}, Stages: []string{"realtime", "save", "pre_submit", "pre_archive"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "发热主诉下必须记录最高体温、持续时间、退热药使用和精神反应。",
			LegalBasis:      "儿科门诊病历要求。",
			SuggestedScript: "请补充儿童发热峰值和伴随反应。",
			Examples:        RuleExamples{Risky: []string{"儿科发热缺最高体温"}, Safe: []string{"最高体温和持续时间完整"}},
		},
		{
			ID:              "emr-rule-117",
			Code:            "emr.pediatrics.weight_dose",
			Name:            "儿童剂量依据完整性",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "high",
			TriggerType:     "semantic",
			Conditions:      emrHardRuleConditions(emrHardRuleOptions{TargetType: "relationship", TargetPath: "patient.weight,prescription", Fields: []string{"patient.weight", "structured.weight", "sections.prescription", "structured.prescription"}, Stages: []string{"pre_submit", "pre_archive", "post_archive_qc"}, Severity: "important", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field", "structured_object"}}),
			Description:     "儿科用药必须关注年龄、体重、剂量、用法和疗程；缺体重或剂量依据时命中。",
			LegalBasis:      "儿科门诊病历要求。",
			SuggestedScript: "请补充体重和剂量依据。",
			Examples:        RuleExamples{Risky: []string{"儿科处方缺体重依据"}, Safe: []string{"处方有体重和剂量依据"}},
		},
		{
			ID:              "emr-rule-118",
			Code:            "emr.pediatrics.feeding_growth",
			Name:            "喂养与生长发育补充",
			Category:        "emr_quality",
			Scope:           "emr",
			Severity:        "medium",
			TriggerType:     "semantic",
			Conditions:      emrRuleObjectConditions(emrRuleObjectOptions{Executor: "hard", TargetType: "field_group", TargetPath: "extensions.pediatrics_growth", Fields: []string{"feeding", "growth", "vaccination"}, Stages: []string{"save", "pre_submit", "post_archive_qc"}, Severity: "notice", BlockSubmit: false, BlockArchive: false, AllowConfirm: true, CountInQC: true, EvidenceTypes: []string{"field"}}),
			Description:     "相关场景下应记录喂养史、生长发育、疫苗接种情况。",
			LegalBasis:      "儿科门诊病历要求。",
			SuggestedScript: "请补充喂养史、生长发育和疫苗接种情况。",
			Examples:        RuleExamples{Risky: []string{"儿科病历无喂养史和生长发育"}, Safe: []string{"喂养史和生长发育完整"}},
		},
	}
}
